import type { ReactNode } from 'react';
export const fmt=(value:number,digits=3)=>Number.isFinite(value)?value.toLocaleString('de-DE',{maximumFractionDigits:digits}).replace('-','−'):'nicht definiert';
// Ein Label ohne for beschriftet sein erstes beschriftbares Kind, hier das <output>; deshalb trägt der Regler seinen Namen selbst.
export function Slider({label,value,onChange,min,max,step=1}:{label:string;value:number;onChange:(v:number)=>void;min:number;max:number;step?:number}){return <label className="foundation-slider"><span>{label}<output>{fmt(value)}</output></span><input type="range" aria-label={label} aria-valuetext={fmt(value)} min={min} max={max} step={step} value={value} onChange={e=>onChange(+e.target.value)}/></label>;}
export function Plot({points,shade,title,xLabel='Wert',bars=false,markers=[],yLabel}:{points:{x:number;y:number;left?:number;right?:number}[];shade?:(x:number)=>boolean;title:string;xLabel?:string;bars?:boolean;markers?:{x:number;label:string}[];yLabel?:string}){
 const finite=points.filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)),low=Math.min(...finite.map(p=>p.left??p.x)),high=Math.max(...finite.map(p=>p.right??p.x)),top=Math.max(.001,...finite.map(p=>p.y))*1.1,sx=(x:number)=>34+(x-low)/Math.max(.001,high-low)*292,sy=(y:number)=>151-y/top*119;
 const line=finite.map(p=>`${sx(p.x)},${sy(p.y)}`).join(' '),dx=finite.length>1?Math.min(24,275/finite.length):24;
 return <svg className="foundation-plot" viewBox="0 0 360 192" role="img" aria-label={title}><title>{title}</title><line x1="34" x2="326" y1="151" y2="151" stroke="#a6b49a"/>{bars?finite.map((p,i)=><rect key={i} x={p.left!==undefined?sx(p.left)+1:sx(p.x)-dx/2} y={sy(p.y)} width={p.right!==undefined&&p.left!==undefined?Math.max(0,sx(p.right)-sx(p.left)-2):dx} height={151-sy(p.y)} fill={shade?.(p.x)?'#9b4b43':'#7d9773'}/>):<>{finite.slice(1).map((p,i)=>{const prev=finite[i];return shade?.((p.x+prev.x)/2)?<polygon key={i} points={`${sx(prev.x)},151 ${sx(prev.x)},${sy(prev.y)} ${sx(p.x)},${sy(p.y)} ${sx(p.x)},151`} fill="#b9807260"/>:null;})}<polyline points={line} fill="none" stroke="#42653c" strokeWidth="2"/></>}{markers.filter(m=>m.x>=low&&m.x<=high).map((m,i)=><g key={i}><line x1={sx(m.x)} x2={sx(m.x)} y1="30" y2="155" stroke="#8b2e2e" strokeDasharray="4 3"/><text x={sx(m.x)} y={20+i*11} textAnchor="middle">{m.label}</text></g>)}<text x="34" y="169">{fmt(low,2)}</text><text x="326" y="169" textAnchor="end">{fmt(high,2)}</text><text x="180" y="188" textAnchor="middle">{xLabel}</text><text x="34" y="15">{yLabel||(bars?'Häufigkeit':'Dichte')}</text></svg>;
}
export function histogram(values:number[],bins=18){const low=Math.min(...values),high=Math.max(...values),step=(high-low||1)/bins;const counts=Array.from({length:bins},(_,i)=>({x:low+(i+.5)*step,y:0,left:low+i*step,right:low+(i+1)*step}));for(const value of values)counts[Math.min(bins-1,Math.floor((value-low)/step))].y++;return counts;}
export function LabFrame({title,children,description='Eigenständiges Lehrmodell. Die Regler verändern dieses Beispiel; die 200 Befragten bleiben erhalten.'}:{title:string;children:ReactNode;description?:string}){return <section className="foundation-lab" aria-label={title}><h2>{title}</h2><p className="lab-description">{description}</p>{children}</section>;}
