import { useState } from 'react';
import { cumulative,density,discrete,distributionMoments,distributionQuantile,initialParameters,type Family,type DistributionParameters } from '../../domain/foundations/probability';
import { LabFrame,Plot,Slider,fmt } from './Charts';
const families:Record<Family,string>={normal:'Normalverteilung',standard_normal:'Standardnormalverteilung',t:'t-Verteilung',chi_square:'χ²-Verteilung',f:'F-Verteilung',bernoulli:'Bernoulli-Verteilung',binomial:'Binomialverteilung',hypergeometric:'Hypergeometrische Verteilung'};
export const distributionFamily:Record<string,Family>={normal_distribution:'normal',standard_normal:'standard_normal',t_distribution:'t',chi_square_distribution:'chi_square',f_distribution:'f',bernoulli_distribution:'bernoulli',binomial_distribution:'binomial',hypergeometric_distribution:'hypergeometric',probability_mass:'binomial',density_function:'normal',theoretical_distribution:'normal',random_variable:'binomial',discrete_continuous:'binomial',cumulative_probability:'normal',theoretical_quantile:'normal'};
export function DistributionLab({id}:{id:string}){
 const [family,setFamily]=useState<Family>(distributionFamily[id]||'normal'),[a,setA]=useState<DistributionParameters>(initialParameters),[target,setTarget]=useState(.8),[view,setView]=useState(id==='cumulative_probability'||id==='theoretical_quantile'?'cdf':'density');
 const change=(key:keyof DistributionParameters)=>(value:number)=>setA(a=>({...a,[key]:value}));
 const integer=discrete(family),quantile=distributionQuantile(family,target,a),lo=integer?0:family==='normal'?a.mu-4*a.sigma:['standard_normal','t'].includes(family)?-Math.max(4,distributionQuantile(family,.99,a)):0;
 const hi=integer?(family==='bernoulli'?1:a.n):family==='normal'?a.mu+4*a.sigma:['standard_normal','t'].includes(family)?-lo:distributionQuantile(family,.99,a),count=integer?hi+1:181;
 const points=Array.from({length:count},(_,i)=>{const x=integer?i:lo+(hi-lo)*(i===0&&(family==='chi_square'||family==='f')?.001:i)/(count-1);return {x,y:density(family,x,a)};});
 if(!integer){for(const t of [.001,.005,.01,.025,.05,.1,.2,.3,.4,.5,.6,.7,.8,.9,.95,.975,.99,target]){const x=distributionQuantile(family,t,a);if(x>=lo&&x<=hi)points.push({x,y:density(family,x,a)});}points.sort((a,b)=>a.x-b.x);}
 let plotted=points;if(view==='cdf'){plotted=integer?points.flatMap(p=>[{x:p.x,y:cumulative(family,p.x-1,a)},{x:p.x,y:cumulative(family,p.x,a)}]):points.map(p=>({x:p.x,y:cumulative(family,p.x,a)}));}
 const moments=distributionMoments(family,a),achieved=cumulative(family,quantile,a),label=integer?'Mögliche Erfolgszahl k':'Wert der Zufallsvariable';
 return <LabFrame title="Eine Verteilung verändern"><label className="foundation-select">Modell<select value={family} onChange={e=>setFamily(e.target.value as Family)}>{Object.entries(families).map(([key,title])=><option value={key} key={key}>{title}</option>)}</select></label>
 {family==='normal'&&<><Slider label="Mittelwert μ" min={-4} max={4} step={.2} value={a.mu} onChange={change('mu')}/><Slider label="Standardabweichung σ" min={.3} max={3} step={.1} value={a.sigma} onChange={change('sigma')}/></>}
 {['t','chi_square','f'].includes(family)&&<Slider label={family==='f'?'Zählerfreiheitsgrade ν₁':'Freiheitsgrade ν'} min={2} max={40} value={a.df} onChange={change('df')}/>}{family==='f'&&<Slider label="Nennerfreiheitsgrade ν₂" min={2} max={80} value={a.df2} onChange={change('df2')}/>}
 {['binomial','hypergeometric'].includes(family)&&<Slider label="Anzahl Ziehungen n" min={1} max={20} value={a.n} onChange={change('n')}/>}{['bernoulli','binomial'].includes(family)&&<Slider label="Erfolgswahrscheinlichkeit p" min={.05} max={.95} step={.05} value={a.p} onChange={change('p')}/>}
 {family==='hypergeometric'&&<><p>Population: N = 30; Ziehen ohne Zurücklegen.</p><Slider label="Erfolge in der Population K" min={1} max={29} value={a.successes} onChange={change('successes')}/></>}
 <Slider label="Gesuchter Anteil bis zur Grenze" min={.01} max={.99} step={.01} value={target} onChange={setTarget}/>
 <label className="foundation-select">Darstellung<select value={view} onChange={e=>setView(e.target.value)}><option value="density">{integer?'Einzelwahrscheinlichkeiten':'Dichte mit Wahrscheinlichkeitsfläche'}</option><option value="cdf">Kumulierte Wahrscheinlichkeit F(x)</option></select></label>
 <Plot title={`${families[family]} ${view==='cdf'?'als kumulierte Wahrscheinlichkeit':'mit schattierter Wahrscheinlichkeit'} bis zum Quantil ${fmt(quantile)}`} points={plotted} bars={integer&&view==='density'} yLabel={view==='cdf'?'F(x) = P(X ≤ x)':integer?'P(X = k)':'Dichte'} shade={view==='density'?x=>x<=quantile:undefined} markers={[{x:quantile,label:'Grenze q'}]} xLabel={label}/>
 <div className="lab-result" aria-live="polite"><span>E(X) = {fmt(moments.mean)}</span><span>Var(X) = {Number.isFinite(moments.variance)?fmt(moments.variance):'nicht endlich'}</span><strong>q = {fmt(quantile)}</strong><span>P(X ≤ q) = {fmt(achieved*100,2)} %</span><span>P(X &gt; q) = {fmt((1-achieved)*100,2)} %</span></div>
 <p>{view==='cdf'?'Die Kurvenhöhe zeigt die bis x gesammelte Wahrscheinlichkeit. Die Grenze q ist das gewählte Quantil.':integer?'Die Masse am Grenzwert gehört zur linken Summe. Ein diskretes Quantil kann mehr als den gesuchten Anteil einschließen.':'Die schattierte Fläche entspricht der kumulierten Wahrscheinlichkeit. Die Höhe der Dichte ist selbst keine Wahrscheinlichkeit.'}</p>
 {!integer&&<small>Die Kurve zeigt einen begrenzten Ausschnitt; Wahrscheinlichkeiten werden über die vollständige Modellverteilung berechnet.</small>}
 </LabFrame>;
}
