import { useMemo,useState } from 'react';
import { normalQuantile,samplingExperiment } from '../../domain/foundations/probability';
import { LabFrame,Plot,Slider,histogram,fmt } from './Charts';
function RunningMean({values,mu}:{values:number[];mu:number}){
 let sum=0;const means=values.map((x,i)=>(sum+=x)/(i+1)),low=Math.min(mu,...means),high=Math.max(mu,...means),pad=Math.max(.1,(high-low)*.1),sx=(i:number)=>38+294*i/(values.length-1),sy=(x:number)=>174-142*(x-low+pad)/(high-low+2*pad);
 return <><svg className="foundation-plot" viewBox="0 0 360 215" role="img" aria-label="Laufender Mittelwert derselben ersten Stichprobe im Vergleich zum wahren Erwartungswert"><line x1="38" x2="332" y1="180" y2="180" stroke="#b5beb1"/><line x1="38" x2="332" y1={sy(mu)} y2={sy(mu)} stroke="#a56d49" strokeDasharray="4 4"/><text x="332" y={sy(mu)-6} textAnchor="end">μ = {fmt(mu)}</text><polyline points={means.map((x,i)=>`${sx(i)},${sy(x)}`).join(' ')} fill="none" stroke="#557a60" strokeWidth="2.5"/><text x="33" y={sy(low)} textAnchor="end">{fmt(low,1)}</text><text x="33" y={sy(high)} textAnchor="end">{fmt(high,1)}</text><text x="38" y="197" textAnchor="middle">1</text><text x="332" y="197" textAnchor="middle">{values.length}</text><text x="186" y="212" textAnchor="middle">Anzahl bislang gezogener Fälle</text></svg><p>Mit mehr Fällen stabilisiert sich der Mittelwert langfristig um μ. Ein einzelner Verlauf kann sich zwischendurch wieder entfernen. Das Gesetz der großen Zahlen beschreibt diese Stabilisierung; der zentrale Grenzwertsatz beschreibt die Form der passend standardisierten Schätzverteilung über viele Stichproben.</p></>;
}
export function SamplingLab({focus}:{focus?:string}){const [n,setN]=useState(20),[shape,setShape]=useState<'normal'|'skewed'|'binary'>('skewed'),[seed,setSeed]=useState(71),[reps,setReps]=useState(400);const sample=useMemo(()=>samplingExperiment(n,reps,shape,seed),[n,reps,shape,seed]),average=sample.means.reduce((s,x)=>s+x,0)/reps,sd=Math.sqrt(sample.means.reduce((s,x)=>s+(x-average)**2,0)/(reps-1)),se=sample.sigma/Math.sqrt(n),half=normalQuantile(.975)*se,covered=sample.means.filter(x=>Math.abs(x-sample.mu)<=half).length;
 return <LabFrame title="Viele Stichproben ziehen" description="Simulation aus einem festgelegten Modell, unabhängig vom Lehrdatensatz. Jede Wiederholung zieht eine neue unabhängige Stichprobe gleicher Größe."><label className="foundation-select">Verteilung der Einzelwerte<select value={shape} onChange={e=>setShape(e.target.value as typeof shape)}><option value="skewed">Rechtsschief · Exponentialmodell, um 1 zentriert</option><option value="normal">Standardnormal</option><option value="binary">Bernoulli · p = 0,3</option></select></label><Slider label="Fälle je Stichprobe n" min={2} max={200} value={n} onChange={setN}/><Slider label="Anzahl Wiederholungen" min={100} max={1000} step={100} value={reps} onChange={setReps}/><button className="lab-action" onClick={()=>setSeed(s=>s+1)}>Neu ziehen</button>
 <Plot title="Histogramm der Einzelwerte der ersten Stichprobe" points={shape==='binary'?[{x:0,y:sample.first.filter(x=>x===0).length},{x:1,y:sample.first.filter(x=>x===1).length}]:histogram(sample.first)} bars xLabel="Einzelwerte · erste Stichprobe"/><Plot title={`Histogramm von ${reps} Stichprobenmittelwerten`} points={histogram(sample.means)} bars xLabel={`Mittelwerte aus jeweils n = ${n} Fällen`} markers={[{x:sample.mu,label:'wahres μ'}]}/>
 <div className="lab-result" aria-live="polite"><span>Wahrer Erwartungswert μ = {fmt(sample.mu)}</span><span>Mittel der Schätzungen = {fmt(average)}</span><strong>Streuung der Schätzungen = {fmt(sd)}</strong><span>Theoretischer Standardfehler σ/√n = {fmt(se)}</span></div>
 <p>Die beiden Histogramme haben eigene Achsen. Größeres n verkleinert die Streuung der Mittelwerte; mehr Wiederholungen machen die Simulation genauer. Die Einzelwerte müssen dadurch nicht normalverteilt werden.</p>
 <details open={focus==='law_large_numbers'||undefined}><summary>Einen Mittelwert beim Wachsen beobachten</summary><RunningMean values={sample.first} mu={sample.mu}/></details>
 <details><summary>Konfidenzintervalle wiederholen</summary><p>Hier bilden wir x̄ ± 1,96 · σ/√n mit bekannter σ. Bei normalverteilten Einzelwerten ist dies ein 95-%-Verfahren; in den anderen Beispielen eine Normalnäherung.</p><svg className="foundation-plot" viewBox="0 0 360 230" role="img" aria-label="Erste 20 Intervalle: grüne überdecken den wahren Parameter, rote nicht">{(()=>{const left=Math.min(sample.mu,...sample.means.slice(0,20).map(x=>x-half)),right=Math.max(sample.mu,...sample.means.slice(0,20).map(x=>x+half)),sx=(x:number)=>30+300*(x-left)/(right-left);return <><line x1={sx(sample.mu)} x2={sx(sample.mu)} y1="10" y2="214" stroke="#4d6347" strokeDasharray="3 4"/>{sample.means.slice(0,20).map((x,i)=><line key={i} x1={sx(x-half)} x2={sx(x+half)} y1={18+i*10} y2={18+i*10} stroke={Math.abs(x-sample.mu)<=half?'#64805b':'#a3473e'} strokeWidth="3"/>)}<text x={sx(sample.mu)} y="228" textAnchor="middle">wahres μ</text></>;})()}</svg><strong>{covered} von {reps} Intervallen überdecken μ ({fmt(100*covered/reps,1)} %).</strong><p>μ bleibt fest; die zufälligen Intervalle wechseln. Abweichungen von 95 % entstehen durch Simulationszufall und bei nichtnormalen Einzelwerten zusätzlich durch die Näherung.</p></details></LabFrame>;
}
