export const deepCopy:Record<string,string>={
 mean:'Ein einzelner großer Wert zieht den Mittelwert mit nach oben. Verändere einen Wert deutlich und beobachte die gestrichelte Linie. Für geordnete Kategorien ist diese Rechnung nicht automatisch sinnvoll: Entscheidend ist, was ihre Abstände bedeuten.',
 variance:'Der Mittelwert wird aus denselben Daten geschätzt. Deshalb ergeben die Abweichungen zusammen 0: Die letzte Abweichung steht durch die übrigen bereits fest. Unter unabhängiger Zufallsziehung aus derselben Verteilung mit endlicher Varianz ist die Division durch n − 1 eine unverzerrte Schätzung der Populationsvarianz.',
 sd:'Die Varianz hat die quadrierte Einheit der gewählten Variable. Die Quadratwurzel bringt die Standardabweichung zurück zur ursprünglichen Einheit. Sie ist kein durchschnittlicher absoluter Abstand vom Mittelwert.',
 z:'Nein. Eine z-Standardisierung verschiebt und skaliert die vorhandenen Werte. Ihre Verteilungsform bleibt erhalten. Die standardisierte Reihe hat bei s > 0 den Mittelwert 0 und die Stichproben-Standardabweichung 1. Eine Prozentposition lässt sich daraus ohne weitere Annahmen nicht ablesen.',
 df:'Bei drei Abweichungen und einer Summe von 0 reichen zwei Angaben: Sind die ersten beiden −2 und +1, muss die letzte +1 sein. Das ist die Bindung durch den bereits geschätzten Mittelwert. Freiheitsgrade zählen hier die verbleibenden freien Abweichungen.',
 pearson:'Pearson beschreibt die lineare Komponente. Ein r nahe 0 kann mit einem deutlichen gekrümmten Muster einhergehen. Einzelne auffällige Punkte können r stark verändern. Die deskriptive Rechnung setzt keine Normalverteilung voraus; Aussagen über eine Grundgesamtheit benötigen zusätzliche Annahmen.',
 scaling:'Skalieren allein verschiebt den Mittelpunkt nicht auf 0. Hier ist der Maßstab die Standardabweichung. Im z-Rechenweg werden die Werte zuerst zentriert und dann skaliert. Nur diese Kombination ergibt z-Werte.',
 metric:'Nein. Zahlen können auch bloße Bezeichnungen sein, etwa 1 = Rot und 2 = Blau. Ob ein Abstand sinnvoll interpretierbar ist, ergibt sich aus der Messung und ihrer inhaltlichen Bedeutung.'
};
