export const workshopUrl='https://rloesung.github.io/RWorkshop/';
export const allbusSource='https://search.gesis.org/research_data/ZA8831';
export const allbusCodebook='https://access.gesis.org/dbk/78527';
export type LearningSession={
 id:number;title:string;phase:string;question:string;intro:string;
 prediction:{question:string;options:string[];correct:number;feedback:string[]};
 insight:string;product:string;preparation:string;concepts:string[];
 chapter:{title:string;path:string};code:string;model?:boolean;
};

export const learningSessions:LearningSession[]=[
 {id:1,title:'Von der Frage zu den Daten',phase:'Fragen & Daten',question:'Was möchten wir über Politik herausfinden?',
 intro:'Wer interessiert sich für Politik? Wie ordnen sich Menschen politisch ein? Aus einer großen Frage wird eine Untersuchung: Du benennst, wen du betrachten möchtest und welche Antworten du dafür brauchst.',
 prediction:{question:'Welche Frage können wir mit einer Bevölkerungsbefragung untersuchen?',options:['Wie verteilt sich politisches Interesse unter den Befragten?','Welche politische Haltung ist die richtige?','Was denkt eine bestimmte Person, die nicht befragt wurde?'],correct:0,feedback:['Ja. Wir können erfasste Antworten beschreiben. Für Schlüsse auf eine größere Bevölkerung brauchen wir zusätzlich das Erhebungsdesign.','Eine Befragung erfasst Einstellungen. Ob eine Haltung richtig ist, ist eine andere, normative Frage.','Wir kennen die Antwort dieser Person nicht. Auch eine gute Stichprobe verrät uns keine unbekannte individuelle Antwort.']},
 insight:'Deine Forschungsfrage bestimmt, welche Daten du brauchst. Ein Variablenname ist noch keine Erklärung dessen, was gemessen wurde.',product:'Ein Projektsteckbrief: Frage, Zielgruppe und zwei passende Variablen. Dazu dein erstes gespeichertes R-Skript.',preparation:'R und RStudio starten, mariposa installieren und ALLBUScompact 2023 bei GESIS beziehen. Ein gemeinsamer Einrichtungstest gehört vor die erste Sitzung.',concepts:['operationalization','series','codebook','sampling'],chapter:{title:'Datenimport und Inspektion',path:'04-Datenimport.html'},code:'summary(codebook(allbus, pa02a, pa01, eastwest, view = FALSE))\nfind_var(allbus, "POLIT")\n# Lies Fragetext und Antwortmöglichkeiten zu pa02a und pa01.'},
 {id:2,title:'Antworten richtig lesen',phase:'Fragen & Daten',question:'Bedeutet eine größere Zahl mehr politisches Interesse?',
 intro:'Zahlen in einer Datentabelle brauchen eine Übersetzung. Beim politischen Interesse bedeutet im ALLBUS eine kleine Zahl starkes Interesse. Eine fehlende Angabe ist keine zusätzliche politische Haltung.',
 prediction:{question:'pa02a enthält den Wert 1. Was bedeutet er laut Codebuch?',options:['Sehr starkes politisches Interesse','Überhaupt kein politisches Interesse','Die erste befragte Person'],correct:0,feedback:['Genau. Die Skala läuft von 1 = sehr stark bis 5 = überhaupt nicht. Größere Zahlen stehen hier für weniger Interesse.','Hier ist es umgekehrt: 5 steht für überhaupt nicht. Die Zahlenrichtung muss aus den Antwortkategorien gelesen werden.','Die 1 ist eine Antwortkategorie. Eine Personenkennung beantwortet eine andere Frage: Zu wem gehört die Angabe?']},
 insight:'Kodierungen ordnen Antworten Zahlen zu. Sie machen Kategorien nicht automatisch zu Messwerten mit gleich großen Abständen.',product:'Ein kleines Variablenverzeichnis mit Bedeutung, Kodierung, Skalenniveau und gültiger Fallzahl.',preparation:'Lies im Workshop die Abschnitte zu Labels und fehlenden Werten. Notiere einen Code, dessen Bedeutung dich überrascht.',concepts:['labels','ordinal','nominal','missing'],chapter:{title:'Datenimport und Inspektion',path:'04-Datenimport.html'},code:'summary(frequency(allbus, pa02a, pa01, eastwest))\nna_frequencies(allbus$pa02a)\nna_frequencies(allbus$pa01)\n# Sondercodes dieser zwei Variablen sind im Startteil bereits als NA gesetzt.'},
 {id:3,title:'Viele Werte zusammenfassen',phase:'Beschreiben & Vergleichen',question:'Können zwei Gruppen gleich weit links oder rechts liegen und sich trotzdem unterscheiden?',
 intro:'Ein Mittelwert fasst vieles zusammen. Die Verteilung zeigt, was dabei verloren geht. Wir beginnen mit fünf erfundenen Selbsteinstufungen und untersuchen danach die Antworten im ALLBUS.',
 prediction:{question:'Gruppe A antwortet 4, 5, 6. Gruppe B antwortet 1, 5, 9. Was trifft zu?',options:['Gleicher Mittelwert, unterschiedliche Streuung','Gruppe B hat einen größeren Mittelwert','Die Gruppen haben dieselbe Verteilung'],correct:0,feedback:['Beide Mittelwerte sind 5. In Gruppe B liegen die Antworten weiter auseinander. Lage und Streuung beantworten verschiedene Fragen.','Auch die 1 zählt mit: In beiden Gruppen ist die Summe 15. Der größere höchste Wert allein bestimmt den Mittelwert nicht.','Die Mitte stimmt überein, die Abstände nicht. Eine einzige Kennzahl beschreibt die Verteilung nicht vollständig.']},
 insight:'Eine politische Mitte in der Verteilung sagt nicht, dass alle dieselbe Haltung haben. Die Streuung und die einzelnen Antwortkategorien gehören zur Beschreibung dazu.',product:'Eine Verteilungsbeschreibung mit Lage, Streuung und einer Grenze der gewählten Kennzahlen.',preparation:'Suche in einer politischen Umfrage eine zusammenfassende Zahl. Welche Verteilung könnte dahinterliegen?',concepts:['empirical_distribution','mean','median','sd'],chapter:{title:'Uni- und bivariate Analyse',path:'07-Uni-Bivariate-Analyse.html'},code:'summary(frequency(allbus, pa01))\ndescribe(allbus, pa01)\nw_mean(allbus, pa01)\nw_median(allbus, pa01)\nw_sd(allbus, pa01)\n# Ungewichtete Beschreibung der gültigen Antworten;\n# Mittelwert/SD setzen hier die metrische Näherung der Skala voraus.'},
 {id:4,title:'Prozent von wem?',phase:'Beschreiben & Vergleichen',question:'Wie vergleichen wir politisches Interesse in Ost und West?',
 intro:'Eine Prozentzahl wird erst mit ihrer Bezugsgruppe verständlich. Wir stellen dieselben Antworten zweimal dar und ändern nur, durch welche Gesamtzahl geteilt wird.',
 prediction:{question:'„30 % der stark Interessierten leben im Osten“ bedeutet dasselbe wie …',options:['… 30 % der Befragten im Osten sind stark interessiert.','… unter den stark Interessierten entfallen 30 % auf den Osten.','… der Osten hat 30 % mehr politisch Interessierte.'],correct:1,feedback:['Die Bezugsgruppen unterscheiden sich. Einmal zählen alle stark Interessierten, einmal alle Befragten im Osten.','Genau. Der Nenner besteht hier aus allen stark Interessierten. Das ist keine Aussage über den Anteil Interessierter innerhalb des Ostens.','Ein Anteil an einer Gruppe ist keine prozentuale Differenz zwischen zwei Gruppen. Dafür bräuchten wir einen gesonderten Vergleich.']},
 insight:'Der Wechsel des Nenners verändert die Frage, die eine Prozentzahl beantwortet. Gewichte beeinflussen zusätzlich, wie stark einzelne Fälle in die Beschreibung eingehen.',product:'Zwei beschriftete Tabellen und zwei korrekte Aussagen zu unterschiedlichen Prozentbasen.',preparation:'Bringe eine Prozentangabe aus einer politischen Nachricht mit und suche ihren Nenner.',concepts:['crosstab','conditional_probability','frequency','weights'],chapter:{title:'Uni- und bivariate Analyse',path:'07-Uni-Bivariate-Analyse.html'},code:'summary(crosstab(allbus, eastwest, pa02a, percentages = "row"))\nsummary(crosstab(allbus, eastwest, pa02a, percentages = "col"))\n# Gewichtete Deskription zum Vergleich, kein Survey-Designtest:\nsummary(crosstab(allbus, eastwest, pa02a,\n         percentages = "row", weights = wghtpew))'},
 {id:5,title:'Zusammenhänge entdecken',phase:'Beschreiben & Vergleichen',question:'Wie hängen politisches Interesse und Links-Rechts-Orientierung zusammen?',
 intro:'Zusammenhang bedeutet zunächst, dass sich Angaben gemeinsam verändern. Wir prüfen eine Vermutung, betrachten die Antworten und unterscheiden eine monotone Beziehung von anderen möglichen Mustern.',
 prediction:{question:'Ein Zusammenhang zwischen Interesse und Orientierung beweist …',options:['… dass Interesse die politische Orientierung verursacht.','… allein noch keine Ursache-Wirkungs-Beziehung.','… dass beide Angaben dasselbe messen.'],correct:1,feedback:['Die Richtung der Ursache ist damit nicht geklärt. Auch andere Merkmale können beide Angaben beeinflussen.','Genau. Ein statistischer Zusammenhang ist ein Ausgangspunkt für weitere Fragen, kein Beleg für eine Wirkung.','Zwei verschiedene Merkmale können zusammenhängen. Zusammenhang und Gleichheit sind unterschiedliche Aussagen.']},
 insight:'Das Vorzeichen hängt auch von der Kodierung ab. Ein kleiner Rangkorrelationswert schließt nicht jede Form von Zusammenhang aus.',product:'Eine begründete Interpretation des Zusammenhangs und eine alternative Erklärung, die die Daten nicht ausschließen.',preparation:'Zeichne zwei mögliche politische Zusammenhänge: einen monotonen und einen nichtmonotonen.',concepts:['pairs','ranks','spearman','causality'],chapter:{title:'Uni- und bivariate Analyse',path:'07-Uni-Bivariate-Analyse.html'},code:'zusammenhang <- spearman_rho(allbus, pa02a, pa01)\nzusammenhang$correlations[, c("rho", "n")]\n# Hier beschreiben wir nur Stärke, Richtung und Fallzahl.\n# Gewöhnliche p-Werte berücksichtigen das ALLBUS-Design nicht.\nsummary(crosstab(allbus, pa02a, pa01, percentages = "row"))\n# Ungewichtet: Zusammenhang unter den gültigen Antwortpaaren.\n# Das Vorzeichen stets zusammen mit beiden Kodierungen lesen.'},
 {id:6,title:'Andere Stichprobe, anderes Ergebnis',phase:'Zufall & Unsicherheit',question:'Warum liefern zwei politische Umfragen nicht genau denselben Wert?',
 intro:'Wir ziehen im Modell immer wieder neue Gruppen von Befragten. Ihre mittlere politische Selbsteinstufung schwankt, obwohl die zugrunde liegende Modellbevölkerung gleich bleibt.',model:true,
 prediction:{question:'Sehr viele Personen werden ausschließlich vor einem Parteitag befragt. Was behebt eine größere Fallzahl?',options:['Automatisch die einseitige Auswahl','Weniger Zufallsschwankung, aber nicht automatisch Auswahlverzerrung','Jede Unsicherheit verschwindet'],correct:1,feedback:['Eine große einseitige Auswahl bleibt einseitig. Die Zusammensetzung der befragten Gruppe ist entscheidend.','Richtig. Präzision und unverzerrte Auswahl sind unterschiedliche Ziele. Viele Fälle allein machen eine Umfrage nicht repräsentativ.','Auch große Stichproben beruhen auf Annahmen und können systematisch von der Zielgruppe abweichen.']},
 insight:'Die Verteilung von Personenwerten und die Verteilung wiederholter Mittelwerte sind zwei verschiedene Verteilungen.',product:'Eine Zeichnung der Stichprobenverteilung und eine Erklärung von Zufallsschwankung gegenüber Auswahlverzerrung.',preparation:'Lies die Begriffe Stichprobe und Grundgesamtheit erneut. Erkläre sie am Beispiel einer Wahlumfrage.',concepts:['random_sampling','sampling_distribution','sampling_bias','se'],chapter:{title:'Uni- und bivariate Analyse',path:'07-Uni-Bivariate-Analyse.html'},code:'set.seed(602)\n# Modell: jede Position 1–10 ist gleich wahrscheinlich; keine ALLBUS-Verteilung.\nmittelwerte <- replicate(500, mean(sample(1:10, 25, replace = TRUE)))\nhist(mittelwerte, main = "500 fiktive Umfragen",\n     xlab = "Mittlere Links-Rechts-Position")\n# Ändere 25 in 100 und starte dieselbe Zeile erneut.'},
 {id:7,title:'Unsicherheit ausdrücken',phase:'Zufall & Unsicherheit',question:'Wie präzise ist die geschätzte politische Mitte?',
 intro:'Ein Mittelwert ist eine Schätzung. Ein Intervall ergänzt die Unsicherheit der Methode. Wir lernen beides zuerst unter klaren Modellannahmen kennen.',model:true,
 prediction:{question:'Viele 95-%-Konfidenzintervalle aus wiederholten Stichproben sollen …',options:['… jeweils 95 % der Personenwerte enthalten.','… langfristig in ungefähr 95 % der Fälle den festen Populationswert überdecken.','… beweisen, dass die Auswahl unverzerrt war.'],correct:1,feedback:['Ein Intervall für einen Mittelwert beschreibt die Unsicherheit der Schätzung, nicht die Spannweite der Personenwerte.','Genau – unter den passenden Modellannahmen. Die 95 % beziehen sich auf das wiederholt angewandte Verfahren.','Die Rechnung prüft die Auswahl nicht nachträglich. Eine systematisch verzerrte Auswahl kann auch ein enges Intervall liefern.']},
 insight:'Ein engeres Intervall steht unter den Modellannahmen für mehr Präzision. Es beweist weder eine gute Messung noch eine unverzerrte Stichprobe.',product:'Eine Punktschätzung mit Intervall und ein Erklärungssatz, der die langfristige Bedeutung von 95 % richtig wiedergibt.',preparation:'Erkläre ohne Formel, warum mehr unabhängige Antworten die Schätzung meist präziser machen.',concepts:['estimator','sd','se','confidence'],chapter:{title:'Uni- und bivariate Analyse',path:'07-Uni-Bivariate-Analyse.html'},code:'w_mean(modell, linksrechts)\nw_sd(modell, linksrechts)\nw_se(modell, linksrechts)\nx <- modell$linksrechts\nn <- length(x)\nn # Fallzahl anzeigen\nse <- sd(x) / sqrt(n)\nmean(x) + c(-1, 1) * qt(.975, df = n - 1) * se\n# Einfaches ungewichtetes Modell; keine designgerechte ALLBUS-Inferenz.'},
 {id:8,title:'Einen Unterschied prüfen',phase:'Zufall & Unsicherheit',question:'Wie beurteilen wir einen Unterschied zwischen zwei Regionen?',
 intro:'In zwei fiktiven Regionen liegen die mittleren Links-Rechts-Antworten nicht genau gleich. Wir verbinden die Größe des Unterschieds mit seiner Unsicherheit und fragen, wie er zum Nullmodell passt.',model:true,
 prediction:{question:'Ein p-Wert von 0,03 bedeutet unter dem Nullmodell und seinen Annahmen …',options:['… die Nullhypothese ist mit 3 % Wahrscheinlichkeit wahr.','… das Ergebnis ist mit 97 % Wahrscheinlichkeit politisch wichtig.','… die Wahrscheinlichkeit einer mindestens so extremen Prüfgröße beträgt 3 %.'],correct:2,feedback:['Der p-Wert setzt das Nullmodell voraus. Er berechnet keine Wahrscheinlichkeit dafür, dass dieses Modell wahr ist.','Statistische Unvereinbarkeit und politische Bedeutung sind verschiedene Fragen. Dafür musst du auch die Größe des Unterschieds betrachten.','Genau. Welche Ergebnisse als extrem gelten, hängt vom Test und seiner vorab festgelegten Alternative ab.']},
 insight:'Der p-Wert ist keine Effektgröße. Ein Unterschied kann statistisch auffällig und inhaltlich klein sein.',product:'Ein kurzer Ergebnisabsatz mit Vergleichsgruppen, Differenz, Unsicherheit, p-Wert und einer Interpretationsgrenze.',preparation:'Schreibe eine falsche p-Wert-Erklärung auf und verbessere sie mit Bezug auf das Nullmodell.',concepts:['hypothesis','test_statistic','t_test','p_value'],chapter:{title:'Uni- und bivariate Analyse',path:'07-Uni-Bivariate-Analyse.html'},code:'vergleich <- t_test(modell, linksrechts, group = region)\nsummary(vergleich)\n# Welch ist die Voreinstellung. Gruppen sind voneinander unabhängig.\n# Fiktive Regionen A/B, keine Befunde über Ost- oder Westdeutschland.'},
 {id:9,title:'Das Verfahren zur Frage wählen',phase:'Erklären & Selbst anwenden',question:'Welches Verfahren passt zu meiner politischen Frage?',
 intro:'Eine Frage nach Antwortanteilen braucht andere Bausteine als eine Frage nach Mittelwerten. Wir greifen die Kreuztabelle wieder auf und vergleichen beobachtete mit unter Unabhängigkeit erwarteten Häufigkeiten.',model:true,
 prediction:{question:'Du untersuchst den Zusammenhang zwischen Region und den fünf Kategorien politischen Interesses. Welcher Einstieg passt?',options:['Eine Kreuztabelle mit den Antwortkategorien','Der Mittelwert der Regionscodes','Eine Korrelation als automatischer Kausalitätsbeweis'],correct:0,feedback:['Ja. Die Tabelle zeigt zunächst, welche Kategorien gemeinsam auftreten. Für einen Test folgen die erwarteten Häufigkeiten und seine Bedingungen.','Region ist hier eine Kategorie. Der Mittelwert ihrer willkürlichen Codes hat keine inhaltliche Bedeutung.','Keine Korrelation beweist automatisch eine Ursache. Zudem verlangt das Maß passende Variablen und eine passende Fragestellung.']},
 insight:'Die Methodenwahl beginnt bei der Frage und dem Erhebungsdesign. Ein Datenformat oder ein kleiner p-Wert wählt das Verfahren nicht für dich aus.',product:'Eine schriftliche Methodenentscheidung für die eigene Analyse mit mindestens einer geprüften Voraussetzung.',preparation:'Bringe deinen Projektsteckbrief und die bisherigen Verteilungen mit.',concepts:['crosstab','expected','chi_square','cramers_v'],chapter:{title:'Uni- und bivariate Analyse',path:'07-Uni-Bivariate-Analyse.html'},code:'summary(crosstab(modell, region, interesse, percentages = "row"))\nchi_square(modell, region, interesse)\ncramers_v(modell, region, interesse)\n# Erwartete Häufigkeiten mitprüfen. Keine repräsentative Bevölkerungsaussage.'},
 {id:10,title:'Mit einem Modell vorhersagen',phase:'Erklären & Selbst anwenden',question:'Was kann eine Gerade über politische Antworten erzählen?',
 intro:'Wir verwenden politisches Interesse, um die Links-Rechts-Position in einem fiktiven Beispiel vorherzusagen. Eine Gerade zeigt eine bestimmte Form von Zusammenhang; die einzelnen Antworten liegen meist daneben.',model:true,
 prediction:{question:'Eine Person liegt zwei Skalenpunkte über dem vorhergesagten Wert. Diese Differenz ist …',options:['… ihr Residuum.','… der p-Wert des Modells.','… der Beweis einer falschen politischen Antwort.'],correct:0,feedback:['Genau: beobachteter Wert minus Vorhersage. Die Residuen zeigen, was das Modell an den Antworten nicht erfasst.','Ein p-Wert ist eine Wahrscheinlichkeit unter einem Nullmodell. Zwei Skalenpunkte sind eine Abweichung in der Einheit der Antwort.','Antworten müssen nicht auf einer Modellgeraden liegen. Das Modell beschreibt einen Zusammenhang und bewertet keine politische Haltung.']},
 insight:'Eine Vorhersage ist keine Erklärung einer Ursache. Politische Orientierung kann zudem nichtlinear mit Interesse zusammenhängen.',product:'Eine erklärte Vorhersage, ein Residuum und eine begründete Grenze des einfachen Modells.',preparation:'Wiederhole Mittelwert, Streuung und Zusammenhang anhand deiner bisherigen Projektgrafik.',concepts:['linear_regression','prediction','residuals','explained_variance'],chapter:{title:'Erklärungsmodelle',path:'09-Erklaerungsmodelle.html'},code:'fit <- linear_regression(modell, formula = linksrechts ~ interesse)\nsummary(fit)\n# Interesse ist im Modell so kodiert: 1 niedrig bis 5 hoch.\n# Lineare Form und metrische Näherung sind Annahmen, keine Eigenschaften jeder politischen Skala.'},
 {id:11,title:'Die eigene Analyse prüfen',phase:'Erklären & Selbst anwenden',question:'Hält meine Antwort einer kritischen Gegenfrage stand?',
 intro:'Jetzt setzt du die Bausteine für deine eigene politische Frage zusammen. Eine gut begründete Beschreibung oder Kreuztabelle ist bereits eine eigenständige Analyse.',
 prediction:{question:'Eine begründete andere Auswertungsentscheidung verändert dein Ergebnis. Was tust du?',options:['Nur das eindrucksvollere Ergebnis berichten','Beide Wege nachvollziehbar vergleichen und die Entscheidung begründen','So lange weitere Tests rechnen, bis einer signifikant wird'],correct:1,feedback:['Die Wahl nur nach dem Ergebnis verdeckt Unsicherheit. Entscheidend ist die fachliche Begründung des Auswertungswegs.','Genau. Die Empfindlichkeit eines Ergebnisses ist selbst eine wichtige Information für seine Einordnung.','Viele nachträgliche Tests erhöhen die Gefahr zufälliger Auffälligkeiten. Die Fragestellung sollte die Analyse führen.']},
 insight:'Nachvollziehbarkeit gehört zum Ergebnis. Berichte auch, welche Entscheidungen deine Aussage beeinflussen.',product:'Ein ausführbares Skript, eine beschriftete Grafik oder Tabelle und ein Ergebnistext mit Grenzen.',preparation:'Vervollständige dein Variablenverzeichnis und sammle offene Fragen zur Auswertung.',concepts:['missing','weights','outliers_influence','causality'],chapter:{title:'Quarto und reproduzierbare Wissenschaft',path:'02-Quarto.html'},code:'summary(codebook(allbus, pa02a, pa01, eastwest, view = FALSE))\n# Beispiel für einen beschreibenden Projektbeginn:\nsummary(crosstab(allbus, eastwest, pa02a, percentages = "row"))\n# Ergänze deine begründete Fragestellung, Fallauswahl und Interpretation.\n# Für Bevölkerungsschlüsse Design und Gewichtung gesondert klären.'},
 {id:12,title:'Ergebnisse erklären',phase:'Erklären & Selbst anwenden',question:'Was dürfen wir aus unserer politischen Analyse schließen?',
 intro:'Du zeigst deinen Weg von der Frage zur Aussage. Andere sollen verstehen, welche Angaben verwendet wurden, warum dein Verfahren passt und was die Untersuchung offenlässt.',
 prediction:{question:'Eine gute Ergebnispräsentation enthält …',options:['… möglichst viele Verfahren ohne weitere Erklärung.','… vor allem den kleinsten gefundenen p-Wert.','… Frage, Daten, begründeten Analyseweg, Ergebnis und Grenzen.'],correct:2,feedback:['Viele Verfahren ersetzen keine nachvollziehbare Antwort. Zeige die Bausteine, die für deine Frage nötig sind.','Ein p-Wert allein beantwortet keine politische Forschungsfrage. Größenordnung, Datenbasis und Grenzen gehören dazu.','Genau. Eine verständliche und begrenzte Aussage ist stärker als eine Schlussfolgerung, die die Daten nicht tragen.']},
 insight:'Dein Analyseweg soll für andere prüfbar sein. Ein beobachteter Zusammenhang und seine politische Deutung bleiben unterscheidbare Schritte.',product:'Ein kurzer Forschungsbericht mit R-Anhang sowie eine individuelle Antwort auf eine neue Analysefrage.',preparation:'Bereite eine kurze Präsentation vor: eine Frage, eine Darstellung, eine Aussage und ihre Grenze.',concepts:['data_export','effect','confidence','causality'],chapter:{title:'Quarto und reproduzierbare Wissenschaft',path:'02-Quarto.html'},code:'# Führe dein vollständiges Projektskript in einer frischen R-Sitzung aus.\n# Halte Paketversionen für deinen Bericht fest:\npackageVersion("mariposa")\nsessionInfo()\n# Gib Datenquelle, Version und alle Auswertungsentscheidungen an.'},
];

const allbusSetup=`# ALLBUScompact 2023 (ZA8831), geprüft gegen das Codebuch v1.3.0.
# Originaldatei nach Registrierung selbst bei GESIS beziehen:
# https://search.gesis.org/research_data/ZA8831
library(mariposa)
allbus <- read_spss(file.choose())
stopifnot(all(c("pa01", "pa02a", "eastwest", "wghtpew") %in% names(allbus)))
# Dokumentierte Sondercodes von Links-Rechts und politischem Interesse.
allbus <- set_na(allbus, pa01 = c(-42, -9), pa02a = c(-42, -9))
# Fehlwerte von Gewichten werden aus der Originaldatei übernommen.
# Kodierung: pa01 = 1 links bis 10 rechts;
# pa02a = 1 sehr starkes bis 5 überhaupt kein Interesse.
# eastwest = 1 West inkl. West-Berlin, 2 Ost inkl. Ost-Berlin.
# Deskriptive Gewichte allein liefern keine vollständige Survey-Inferenz.
`;
const modelSetup=`# Eigenständiger politikwissenschaftlicher Modellversuch.
# Vollständig erfunden: keine ALLBUS-Fälle und keine empirischen Befunde.
library(mariposa)
set.seed(2023)
modell <- data.frame(
  region = factor(rep(c("Region A", "Region B"), each = 100)),
  interesse = sample(1:5, 200, replace = TRUE),
  linksrechts = sample(1:10, 200, replace = TRUE)
)
# Modell: unabhängige Antworten; Skalenabstände für Mittelwert/Regression
# als gleich groß behandelt. Interesse: 1 niedrig bis 5 hoch.
`;
export function learningScript(session:LearningSession){return `# Statistikatlas · Sitzung ${session.id}: ${session.title}\n# ${session.question}\n\n${session.model?modelSetup:allbusSetup}\n${session.code}\n`;}
export function politicalSummary(values:number[]){const sorted=[...values].sort((a,b)=>a-b),n=values.length,mean=values.reduce((sum,x)=>sum+x,0)/n;return {mean,median:n%2?sorted[(n-1)/2]:(sorted[n/2-1]+sorted[n/2])/2,sd:Math.sqrt(values.reduce((sum,x)=>sum+(x-mean)**2,0)/(n-1))};}
