suppressPackageStartupMessages({library(mariposa); library(dplyr)})
options(warn = -1)
allbus <- read_spss("/Users/yannickdiehl/Documents/Universität Marburg/Lehre/Methoden Ib B.A./ZA8831_v1-3-0.sav")
cat("wghtpew-Stufen je Region und Modus:\n")
print(allbus %>% mutate(w = round(as.numeric(wghtpew), 4)) %>% count(eastwest, mode, w))
allbus <- allbus %>% mutate(konf = rec(rd01, rules = "1:2=1 [evangelisch]; 3=2 [katholisch]; 4:5=3 [andere]; 6=4 [keine]; else=NA"),
                            educ5 = rec(educ, rules = "1:5=copy; else=NA"))
res <- read.csv("deck_results.csv")
cards <- c("eastwest","konf","age","ep01","ep03","pa02a","id02","educ5","rp01","gs01","pa01","ls01")
r <- res %>% filter(var %in% cards)
# permutation baseline for V (weighted)
set.seed(1)
r$V_zufall <- sapply(r$var, function(v) { d <- allbus %>% filter(!is.na(ps03), !is.na(.data[[v]])); mean(replicate(10, { d$ps03 <- sample(d$ps03); cramers_v(d, ps03, !!sym(v), weights = wghtpew) })) })
r <- r %>% mutate(rk_V = rank(-abs(V_w)), rk_g = rank(-abs(g_w)), rk_tau = rank(-abs(tau_w)), rk_r = rank(-abs(r_w)))
print(r %>% select(var, n, V_w, V_zufall, g_w, tau_w, rho, r_w, rk_V, rk_g, rk_tau, rk_r, tau_West, tau_Ost, V_West, V_Ost) %>% mutate(across(where(is.numeric), ~round(.x, 3))), width = 250)
