suppressPackageStartupMessages({library(mariposa); library(dplyr)})
allbus <- read_spss("/Users/yannickdiehl/Documents/Universität Marburg/Lehre/Methoden Ib B.A./ZA8831_v1-3-0.sav")
sub <- allbus %>% filter(!is.na(ps03), !is.na(ep01))
cat("n =", nrow(sub), "\n")
t1 <- system.time(k1 <- sub[1:800,] %>% kendall_tau(ps03, ep01, weights = wghtpew))
cat("n=800 weighted secs:", t1[3], " tau:", k1$correlations$tau[1] %||% NA, "\n"); flush.console()
str(k1, max.level = 1)
t0 <- system.time(k0 <- allbus %>% kendall_tau(ps03, ep01))
cat("full unweighted secs:", t0[3], "\n"); print(k0)
t2 <- system.time(k2 <- allbus %>% kendall_tau(ps03, ep01, weights = wghtpew))
cat("full weighted secs:", t2[3], "\n"); print(k2)
