suppressPackageStartupMessages({library(mariposa); library(dplyr)})
allbus <- read_spss("/Users/yannickdiehl/Documents/Universität Marburg/Lehre/Methoden Ib B.A./ZA8831_v1-3-0.sav")
d <- allbus %>% mutate(demo = rec(ps03, rules = "rev"))
cat("overlap ps03 & pt03:", sum(!is.na(d$ps03) & !is.na(d$pt03)), "\n")
cat("overlap ps03 & pe01:", sum(!is.na(d$ps03) & !is.na(d$pe01)), "\n")
cat("overlap ps03 & pa01:", sum(!is.na(d$ps03) & !is.na(d$pa01)), "\n")
fitone <- function(y, x, w = NULL) {
  yy <- as.numeric(d[[y]]); xx <- as.numeric(d[[x]]); ww <- if (is.null(w)) rep(1, nrow(d)) else as.numeric(d[[w]])
  ok <- !is.na(yy) & !is.na(xx) & !is.na(ww)
  m <- lm(yy[ok] ~ xx[ok], weights = ww[ok])
  s <- summary(m)
  c(n = sum(ok), a = unname(coef(m)[1]), b = unname(coef(m)[2]), r2 = s$r.squared, sy = sqrt(sum(ww[ok]*(yy[ok]-weighted.mean(yy[ok],ww[ok]))^2)/sum(ww[ok])), se = sqrt(sum(ww[ok]*residuals(m)^2)/sum(ww[ok])))
}
xs <- c("age","pa01","pt03","pt12","pt02","pt14","ls01","ep03","ep01","pa02a","id02","hs01","di08c","pe01")
res <- t(sapply(xs, function(x) fitone("demo", x)))
resw <- t(sapply(xs, function(x) fitone("demo", x, "wghtpew")))
cat("\nY = demo (ps03 rev, 6 = sehr zufrieden), unweighted\n"); print(round(res, 4))
cat("\nweighted\n"); print(round(resw, 4))
cat("\nY = ls01\n")
xs2 <- c("age","ep03","hs01","di08c","id02","pa01","pt03")
d$ls <- as.numeric(d$ls01)
print(round(t(sapply(xs2, function(x) fitone("ls01", x, "wghtpew"))),4))
