suppressPackageStartupMessages({library(mariposa); library(dplyr)})
allbus <- read_spss("/Users/yannickdiehl/Documents/Universität Marburg/Lehre/Methoden Ib B.A./ZA8831_v1-3-0.sav")
allbus %>% fre(pv01) %>% summary()
allbus %>% fre(pv01, weights = wghtpew) %>% summary()
allbus %>% fre(mode) %>% summary()
