suppressPackageStartupMessages({library(mariposa); library(dplyr)})
allbus <- read_spss("/Users/yannickdiehl/Documents/Universität Marburg/Lehre/Methoden Ib B.A./ZA8831_v1-3-0.sav")
print(attr(allbus$ma02,"labels")); print(attr(allbus$mm05,"labels"))
d <- allbus %>% mutate(selbst = rec(mode, rules = "2=0 [Interview]; 3:4=1 [selbst ausgefuellt]"))
d %>% oneway_anova(ma02, mm05, ls01, age, group = mode)
d %>% t_test(ma02, mm05, ls01, age, group = selbst)
d %>% group_by(mode) %>% pearson_cor(ma02, mm01, mm05)
