suppressPackageStartupMessages({library(mariposa); library(dplyr)})
allbus <- read_spss("/Users/yannickdiehl/Documents/Universität Marburg/Lehre/Methoden Ib B.A./ZA8831_v1-3-0.sav")
cat("n =", nrow(allbus), "\n")
print(table(allbus$mode, useNA="ifany"))
print(attr(allbus$mode, "labels"))
print(table(as.numeric(allbus$splt23_3), as.numeric(allbus$mode), useNA="ifany"))
print(attr(allbus$splt23_3, "labels"))
print(table(as.numeric(allbus$xr21), useNA="ifany"))
print(table(as.numeric(allbus$substudy), as.numeric(allbus$mode), useNA="ifany"))
print(attr(allbus$substudy, "labels"))
print(class(allbus$xr21)); print(head(allbus$xr21))
