suppressMessages({library(mariposa); library(dplyr)})
allbus <- read_spss("/Users/yannickdiehl/Documents/Universität Marburg/Lehre/Methoden Ib B.A./ZA8831_v1-3-0.sav")
allbus <- allbus %>% to_dummy(dg03, ref = 4)
allbus <- allbus %>% to_dummy(dg03, ref = 1)
print(grep("dg03", names(allbus), value = TRUE))
r <- allbus %>% linear_regression(ps03 ~ dg03_2 + dg03_3 + dg03_4, weights = wghtpew)
print(round(coef(r),3))
nd <- data.frame(dg03_2 = c(0,1,0,0), dg03_3 = c(0,0,1,0), dg03_4 = c(0,0,0,1))
print(round(predict(r, newdata = nd),3))
