suppressMessages({library(mariposa); library(dplyr)})
allbus <- read_spss("/Users/yannickdiehl/Documents/Universität Marburg/Lehre/Methoden Ib B.A./ZA8831_v1-3-0.sav")
allbus <- allbus %>% to_dummy(dg03)
print(grep("dg03", names(allbus), value = TRUE))
allbus %>% linear_regression(ps03 ~ dg03_1 + dg03_2 + dg03_3 + dg03_4, weights = wghtpew) %>% summary(anova_table = FALSE, descriptives = FALSE)
r <- allbus %>% linear_regression(ps03 ~ dg03_2 + dg03_3 + dg03_4, weights = wghtpew)
print(round(coef(r),3))
r3 <- allbus %>% linear_regression(ps03 ~ dg03_1 + dg03_2 + dg03_4, weights = wghtpew)
print(round(coef(r3),3))
