import { ArrowUpRight, BookOpen, Map, ArrowRight, ArrowLeft, Copy, Download, Clock3, RotateCcw, ChevronDown } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { learningSessions, learningScript, politicalSummary, workshopUrl, allbusSource, allbusCodebook } from '../domain/learningPath';
import { titleFor, ref } from '../domain/learning';
import { downloadText } from '../domain/mariposa';

const format=(value:number)=>value.toLocaleString('de-DE',{maximumFractionDigits:2});
function PoliticalSandbox({onConcept}:{onConcept:(id:string)=>void}){
 const [last,setLast]=useState(6),[symbol,setSymbol]=useState<'sum'|'n'|'mean'>('mean');
 const values=[2,3,4,5,last],summary=politicalSummary(values);
 return <section className="political-sandbox" aria-labelledby="sandbox-title"><span className="learning-eyebrow">KLEINER MODELLVERSUCH · ERFUNDENE ANTWORTEN</span><h3 id="sandbox-title">Eine Antwort verändert das Bild.</h3><p>Fünf fiktive Befragte ordnen sich auf einer Skala von 1 (links) bis 10 (rechts) ein. Ändere die fünfte Antwort und beobachte die Kennwerte.</p><div className="political-values" aria-label={`Die fünf Antworten: ${values.join(', ')}`}>{values.map((value,i)=><span key={i} className={i===4?'editable':''}><small>Person {i+1}</small><strong>{value}</strong></span>)}</div><label className="political-slider" htmlFor="political-answer"><span>Antwort von Person 5 <output>{last}</output></span><input id="political-answer" type="range" min="1" max="10" step="1" value={last} onChange={e=>setLast(Number(e.target.value))}/><span className="scale-ends"><span>1 · links</span><span>10 · rechts</span></span></label><div className="political-results" aria-live="polite"><div><span>Mittelwert</span><strong>{format(summary.mean)}</strong></div><div><span>Median</span><strong>{format(summary.median)}</strong></div><div><span>Standardabweichung s</span><strong>{format(summary.sd)}</strong></div></div><div className="learning-formula" role="group" aria-label="Bestandteile der Mittelwertformel"><button aria-pressed={symbol==='mean'} onClick={()=>setSymbol('mean')}>x̄</button><span>=</span><button aria-pressed={symbol==='sum'} onClick={()=>setSymbol('sum')}>Σ xᵢ</button><span>÷</span><button aria-pressed={symbol==='n'} onClick={()=>setSymbol('n')}>n</button><span>= {values.reduce((a,b)=>a+b,0)} ÷ 5 = {format(summary.mean)}</span></div><p className="formula-explanation" role="status">{symbol==='mean'?'x̄ ist der Mittelwert: die Summe, gleichmäßig auf alle fünf Antworten verteilt.':symbol==='sum'?`Σ fordert uns auf, alle Antworten zu addieren: ${values.join(' + ')} = ${values.reduce((a,b)=>a+b,0)}.`:'n zählt die gültigen Antworten. Hier sind es fünf. Die Anzahl ändert sich nicht, wenn eine Person anders antwortet.'}</p><p className="learning-small">Für diese Rechenübung nehmen wir gleich große Skalenabstände an. Der Median verwendet die Reihenfolge. s wird mit dem Teiler n − 1 berechnet.</p><div className="learning-inline-actions"><button onClick={()=>{setLast(6);setSymbol('mean');}}><RotateCcw size={15}/>Versuch zurücksetzen</button><button onClick={()=>onConcept('sd')}>Streuung in der Karte<ArrowUpRight size={15}/></button></div></section>;
}

export function LearningPath({onConcept,sessionIndex=0,onSessionChange}:{onConcept:(id:string)=>void;sessionIndex?:number;onSessionChange:(index:number)=>void}){
 const session=learningSessions[sessionIndex]||learningSessions[0],container=useRef<HTMLElement>(null),heading=useRef<HTMLHeadingElement>(null),initial=useRef(true);
 const [answers,setAnswers]=useState<Record<number,number>>({}),[copyStatus,setCopyStatus]=useState('');
 const answer=answers[session.id];
 useEffect(()=>{setCopyStatus('');if(initial.current){initial.current=false;return;}container.current?.scrollTo({top:0,behavior:'instant'});heading.current?.focus({preventScroll:true});},[session.id]);
 async function copy(){try{await navigator.clipboard.writeText(learningScript(session));setCopyStatus('Das vollständige R-Skript ist kopiert.');}catch{setCopyStatus('Bitte lade das R-Skript herunter; Kopieren ist hier nicht verfügbar.');}}
 function move(index:number){if(index>=0&&index<learningSessions.length)onSessionChange(index);}
 return <main ref={container} className="learning-path" id="learning-main"><aside className="learning-rail"><a className="learning-brand" href="#learning-main">Statistikatlas<span>.</span></a><p className="learning-eyebrow">DEIN LERNWEG · ENTWURF</p><h1>Politik mit Daten verstehen.</h1><p>12 Sitzungen · je 90 Minuten<br/>Vom ersten Blick zur eigenen Analyse.</p><nav aria-label="Zwölf Sitzungen"><ol>{learningSessions.map((s,i)=><li key={s.id} className={i===sessionIndex?'current':''}><button aria-current={i===sessionIndex?'step':undefined} onClick={()=>move(i)}><span>{String(s.id).padStart(2,'0')}</span><strong>{s.title}</strong>{i===sessionIndex&&<ArrowRight size={15}/>}</button></li>)}</ol></nav><a className="learning-source" href={workshopUrl} target="_blank" rel="noreferrer"><BookOpen size={17}/>Zum R-Workshop<ArrowUpRight size={15}/></a><p className="learning-rail-note">Jede Sitzung verbindet eine Frage, einen Versuch und einen nächsten Schritt für dein Projekt. Du kannst die Reihenfolge frei erkunden.</p></aside>
 <article className="learning-lesson"><div className="learning-meta"><span>Sitzung {String(session.id).padStart(2,'0')} / 12</span><span>{session.phase}</span><span><Clock3 size={14}/>90 Min.</span></div><h2 id="learning-heading" ref={heading} tabIndex={-1}>{session.question}</h2><p className="learning-lead">{session.intro}</p><div className="learning-dataset-label">{session.model?'Modellversuch · ausdrücklich erfundene politische Antworten':'Datenbezug · ALLBUScompact 2023'}</div>
 <section className="learning-prompt"><span className="learning-eyebrow">ERST EINMAL VERMUTEN</span><h3>{session.prediction.question}</h3><div className="learning-answers">{session.prediction.options.map((text,i)=><button key={`${session.id}-${i}`} aria-pressed={answer===i} onClick={()=>setAnswers(previous=>({...previous,[session.id]:i}))}><span>{text}</span><ArrowRight size={18}/></button>)}</div>{answer!==undefined&&<p className="learning-feedback" role="status">{session.prediction.feedback[answer]}</p>}</section>
 {session.id===3&&<PoliticalSandbox onConcept={onConcept}/>}
 <section className="learning-body"><span className="learning-eyebrow">DEIN AUFTRAG</span><h3>Ausprobieren. Beobachten. Begründen.</h3><ol className="learning-steps">{session.steps.map((step,i)=><li key={step}><span>{i+1}</span><p>{step}</p></li>)}</ol><div className="learning-insight"><strong>Der Gedanke dahinter</strong><p>{session.insight}</p></div><div className="learning-result"><strong>Das nimmst du für dein Projekt mit</strong><p>{session.product}</p></div></section>
 <details className="learning-r" key={`r-${session.id}`}><summary><span><span className="learning-eyebrow">DIE IDEE IN R WEITERFÜHREN</span><strong>Mit mariposa untersuchen</strong></span><ChevronDown size={21}/></summary><div className="learning-r-body"><p>{session.model?'Das Skript erzeugt einen eigenständigen Modellversuch. Die Zahlen sind erfunden; sie berichten keine politischen Befunde.':'Für dieses Skript brauchst du deine eigene SPSS-Datei von ALLBUScompact 2023. Der Startteil hilft beim Einlesen und kennzeichnet die dokumentierten Sondercodes.'}</p><pre className="learning-code"><code>{session.code}</code></pre><div className="learning-inline-actions"><button onClick={copy}><Copy size={16}/>Ganzes Skript kopieren</button><button onClick={()=>downloadText(`Statistikatlas-Sitzung-${String(session.id).padStart(2,'0')}.R`,learningScript(session))}><Download size={16}/>R-Skript herunterladen</button></div>{copyStatus&&<p role="status" className="learning-small">{copyStatus}</p>}<details className="learning-start-code"><summary>Startteil und Datenvorbereitung ansehen</summary><pre className="learning-code"><code>{learningScript(session).split(session.code)[0]}</code></pre></details><p className="learning-small">Führe das Skript in R aus. Der Lernpfad zeigt keine aus ALLBUS berechneten Ergebnisse. Die Modellrechnungen zur Inferenz ersetzen keine Auswertung des komplexen Stichprobendesigns.</p><a className="learning-source" href={workshopUrl+session.chapter.path} target="_blank" rel="noreferrer">Im Workshop nachlesen: {session.chapter.title}<ArrowUpRight size={15}/></a></div></details>
 <aside className="learning-map-help"><Map size={22}/><div><strong>Diese Bausteine helfen dir beim Einordnen.</strong><p>Öffne einen Begriff in der freien Karte. Dein Platz im Lernpfad bleibt erhalten.</p><div>{session.concepts.map(id=><button key={id} onClick={()=>onConcept(id)}>{titleFor(ref(id))}<ArrowUpRight size={15}/></button>)}</div></div></aside>
 <details className="learning-preparation"><summary>Für davor und danach · etwa 15 Minuten</summary><p>{session.preparation}</p><p>Für 90 Minuten: 10 Min. Rückblick · 15 Min. Einstieg · 20 Min. Experiment · 20 Min. R · 20 Min. eigenes Projekt · 5 Min. Abschlussfrage.</p></details>
 <details className="learning-data"><summary>Datenbasis und hilfreiche Quellen</summary><p>Der Lernpfad verwendet politisches Interesse (<code>pa02a</code>), Links-Rechts-Selbsteinstufung (<code>pa01</code>) und Wohngebiet (<code>eastwest</code>) aus ALLBUScompact 2023. Frage und Kodierung wurden im GESIS-Codebuch zu Version 1.3.0 geprüft.</p><dl><dt>Politisches Interesse · pa02a</dt><dd>1 = sehr stark bis 5 = überhaupt nicht. Fehlcodes: −42 und −9. <a href={allbusCodebook+'#page=392'} target="_blank" rel="noreferrer">Frage nachlesen</a></dd><dt>Links–rechts · pa01</dt><dd>1 = links bis 10 = rechts. Fehlcodes: −42 und −9. <a href={allbusCodebook+'#page=402'} target="_blank" rel="noreferrer">Frage nachlesen</a></dd><dt>Wohngebiet · eastwest</dt><dd>West einschließlich West-Berlin / Ost einschließlich Ost-Berlin. <a href={allbusCodebook+'#page=71'} target="_blank" rel="noreferrer">Kodierung nachlesen</a></dd></dl><p>Originaldaten erhältst du nach Registrierung bei GESIS. Im Lernpfad sind keine ALLBUS-Einzelfälle hinterlegt. Die Modellversuche und die 200 synthetischen Befragten der freien Karte sind eigenständige Lehrbeispiele.</p><a className="learning-source" href={allbusSource} target="_blank" rel="noreferrer">ALLBUScompact 2023 · ZA8831 bei GESIS<ArrowUpRight size={15}/></a><a className="learning-source" href={workshopUrl} target="_blank" rel="noreferrer">R Workshop – Sozialwissenschaften · Diehl & Moosdorf<ArrowUpRight size={15}/></a><p>Faktorenanalyse, Skalenbildung, ANOVA sowie multiple und logistische Regression bleiben als Vertiefungen in der Karte erreichbar. Für den Einstieg genügt ein begründeter, überschaubarer Analyseweg.</p></details>
 <nav className="learning-pagination" aria-label="Zwischen Sitzungen wechseln"><button disabled={sessionIndex===0} onClick={()=>move(sessionIndex-1)}><ArrowLeft size={17}/>Vorherige Sitzung</button>{sessionIndex<11?<button onClick={()=>move(sessionIndex+1)}>Weiter zu Sitzung {session.id+1}<ArrowRight size={17}/></button>:<button onClick={()=>move(0)}>Zum Anfang des Lernwegs<RotateCcw size={16}/></button>}</nav></article></main>;
}
