import { entryById } from '../domain/mariposaCatalog';
import { memo, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ReactFlow, Background, Controls, MiniMap, Handle, Position, MarkerType, useReactFlow, useStore, type Node, type NodeProps, type Viewport } from '@xyflow/react';
import { conceptById } from '../domain/concepts';
import { isOperation, titleFor, valueFor, displayValue, unitFor, type Ref, type LessonContext } from '../domain/learning';
import { landmarks, mapTitles, referenceInMap, incomingPaths, routeAfterSelection } from '../domain/network';

import { restingPlaces, gravityMembers, dragLayout, type MapLayout } from '../domain/mapLayout';
import { mapConcepts, mapIds, mapAnchor, visibleRelations, visibleRelated } from '../domain/visibleNetwork';

type MapData={reference:Ref;context:LessonContext;active:boolean;related:boolean;hovered:boolean;visited:boolean;onSelect:(r:Ref)=>void;onHover:(id:string|null)=>void};
type MapNode=Node<MapData,'concept'>;
const sides=[['left',Position.Left],['right',Position.Right],['top',Position.Top],['bottom',Position.Bottom]] as const;
function Concept({data:d}:NodeProps<MapNode>){const r=d.reference,c=conceptById[r.id];return <article className={`network-node ${entryById[r.id]&&!entryById[r.id].existing?'package-node':''} concept-${r.id} ${landmarks.has(r.id)?'landmark':''} category-${c.category} ${d.active?'selected':''} ${d.related?'related':'muted'} ${d.hovered?'hovered':''} ${d.visited?'visited':''}`}>
 {sides.map(([side,position])=><Handle key={`in-${side}`} id={`in-${side}`} type="target" position={position}/>)}
 <span className="node-drag-grip" title="Ziehen, um diesen Begriff zu verschieben" aria-hidden="true">⠿</span><button className="nodrag" onClick={()=>d.onSelect(r)} onPointerEnter={()=>d.onHover(r.id)} onPointerLeave={()=>d.onHover(null)} onFocus={()=>d.onHover(r.id)} onBlur={()=>d.onHover(null)} aria-label={`${titleFor(r)} im Netzwerk erkunden`} aria-pressed={d.active}><span className="network-node-kind">{entryById[r.id]?.variants.length?'Verfahren':c.category==='operation'?'Transformation':c.category==='data'?'Grundlage':'Baustein'}</span><strong>{r.use==='z'&&['crossproduct','crossproduct_sum'].includes(r.id)?(r.id==='crossproduct'?'z-Produkte':'z-Produktsumme'):mapTitles[r.id]||titleFor(r)}</strong><span className="network-node-value">{!isOperation(r)&&valueFor(r,d.context)!==null?`${['validn','count','df','crossproduct','crossproduct_sum','covariance','sd_product','pearson'].includes(r.id)?'':r.variable.toUpperCase()+' · '}${displayValue(r,d.context)} ${unitFor(r,d.context)}`:c.short}</span><span className="network-node-dot" aria-hidden="true"/></button>
 {sides.map(([side,position])=><Handle key={`out-${side}`} id={`out-${side}`} type="source" position={position}/>)}</article>;}
const MemoConcept=memo(Concept,(a,b)=>a.data.context===b.data.context&&JSON.stringify(a.data.reference)===JSON.stringify(b.data.reference)&&['active','related','hovered','visited'].every(key=>a.data[key as 'active']===b.data[key as 'active']));
export const nodeTypes={concept:MemoConcept};
export const nodeInteraction={style:{pointerEvents:'all' as const},zIndex:3,draggable:true,selectable:false,focusable:false};
export type CameraRequest={id:number;kind:'all'|'focus'|'restore'|'ensure'|'none';viewport?:Viewport};
export function NetworkMap({selected,context,hovered,visited,onSelect,onHover,onViewport,onViewportReader,camera,trace=false,inspectorOpen=false,onBackground,highlightRef,layout,onLayoutReader,contextAnchor,gravity=false,onLayoutChange}:{selected:Ref|null;context:LessonContext;hovered:string|null;visited:Set<string>;onSelect:(r:Ref)=>void;onHover:(id:string|null)=>void;onViewport:(v:Viewport)=>void;onViewportReader:(read:()=>Viewport)=>void;camera:CameraRequest;trace?:boolean;inspectorOpen?:boolean;onBackground?:()=>void;highlightRef?:Ref;layout?:MapLayout;contextAnchor?:Ref;onLayoutReader?:(read:()=>MapLayout)=>void;gravity?:boolean;onLayoutChange?:(layout:MapLayout)=>void}){
 const destinations=layout||restingPlaces,positions=destinations;
 const [edgeHover,setEdgeHover]=useState<string|null>(null);
 const [dragged,setDragged]=useState<{id:string;position:{x:number;y:number}}|null>(null);
 const handlers=useRef({onSelect,onHover,onLayoutChange});handlers.current={onSelect,onHover,onLayoutChange};
 const selectNode=useCallback((r:Ref)=>handlers.current.onSelect(r),[]),hoverNode=useCallback((id:string|null)=>handlers.current.onHover(id),[]);
 const focus=mapAnchor(selected,contextAnchor);
 const drawn=useRef(positions);drawn.current=positions;
 useEffect(()=>{onLayoutReader?.(()=>drawn.current);},[onLayoutReader]);
 const zoom=useStore(s=>s.transform[2]);
 const flow=useReactFlow(),container=useRef<HTMLDivElement>(null),mounted=useRef(false);
 const mapReference=highlightRef||(hovered?referenceInMap(hovered,selected,context.route,contextAnchor):selected),hoverRoute=mapReference?routeAfterSelection(selected,mapReference,context.route):context.route;
 const relations=useMemo(()=>visibleRelations(mapReference,hoverRoute,contextAnchor||selected),[mapReference?.id,mapReference?.use,mapReference?.variable,mapReference?.basis,hoverRoute,contextAnchor,selected]);
 const hoveredAnchor=hovered?mapAnchor(mapReference,contextAnchor||selected):null;
 const hoverPath=useMemo(()=>hoveredAnchor?incomingPaths(hoveredAnchor.id,relations):null,[hoveredAnchor?.id,relations]);
 const related=hoverPath?.nodes||visibleRelated(selected,trace,context.route,contextAnchor),hoverNeighbors=hoverPath?.nodes;
 const tracedEdges=trace&&focus?incomingPaths(focus.id,relations).edges:undefined;
 const conceptNodes:MapNode[]=mapConcepts.map(c=>({id:c.id,type:'concept',position:dragged?.id===c.id?dragged.position:positions[c.id],...nodeInteraction,data:{reference:highlightRef?.id===c.id?highlightRef:referenceInMap(c.id,mapReference,context.route,contextAnchor),context,active:focus?.id===c.id,related:related.has(c.id)||!!hoverNeighbors?.has(c.id),hovered:hoveredAnchor?.id===c.id,visited:visited.has(c.id),onSelect:selectNode,onHover:hoverNode}}));
 const edges=relations.filter(e=>!e.alternative).map(e=>{const a=positions[e.source],b=positions[e.target],dx=b.x-a.x,dy=b.y-a.y,vertical=Math.abs(dy)>Math.abs(dx),sourceSide=vertical?(dy>0?'bottom':'top'):(dx>0?'right':'left'),targetSide=vertical?(dy>0?'top':'bottom'):(dx>0?'left':'right'),direct=e.source===focus?.id||e.target===focus?.id,hover=hoverPath?.edges.has(e.id),traced=tracedEdges?.has(e.id),strong=!e.alternative&&(hoverPath?hover:direct||traced);return {id:e.id,source:e.source,target:e.target,sourceHandle:`out-${sourceSide}`,targetHandle:`in-${targetSide}`,type:'default',label:edgeHover===e.id?e.label:undefined,style:{stroke:e.kind==='meaning'?'#718798':e.kind==='condition'?'#98714e':strong?'#6b8266':'#bfc7b6',strokeWidth:strong?2.1:.9,opacity:(selected||hovered)&&!strong?.18:strong?1:e.kind==='meaning'?.14:e.kind==='condition'?.24:.35,strokeDasharray:e.alternative?'3 7':e.kind==='meaning'?'2 6':e.kind==='condition'?'7 4':e.kind==='optional'?'2 5':undefined},markerEnd:{type:MarkerType.ArrowClosed,color:strong?'#6b8266':'#bfc7b6',width:16,height:16},labelStyle:{fontSize:12,fill:'#43553e'},labelBgStyle:{fill:'#faf8f3',fillOpacity:.94},labelBgPadding:[6,4] as [number,number],labelBgBorderRadius:3,focusable:false,zIndex:strong?2:0};});
 const nodes=conceptNodes;
 function bounds(){const width=container.current?.clientWidth||800,height=container.current?.clientHeight||600,mobile=width<=760;return {width:width-(inspectorOpen&&!mobile?434:0),height:height-(inspectorOpen&&mobile?height*.51:0),mobile};}
 function fit(ids:string[],duration:number,readable=false){const b=bounds(),points=ids.map(id=>destinations[id]).filter(Boolean),left=Math.min(...points.map(p=>p.x)),right=Math.max(...points.map(p=>p.x+196)),top=Math.min(...points.map(p=>p.y))-120,bottom=Math.max(...points.map(p=>p.y+112)),zoom=Math.max(.05,Math.min(1.1,(b.width-80)/(right-left),(b.height-190)/(bottom-top)));if(readable&&zoom<(b.mobile?.8:.85)){ensure(duration,true);return;}void flow.setViewport({x:b.width/2-(left+right)/2*zoom,y:(b.height+100)/2-(top+bottom)/2*zoom,zoom},{duration});}
 function ensure(duration:number,center=false){
  if(!focus)return;const p=destinations[focus.id],b=bounds(),v=flow.getViewport(),zoom=Math.max(v.zoom,b.mobile?.8:.85),cx=(p.x+98)*v.zoom+v.x,cy=(p.y+56)*v.zoom+v.y;
  const left=48,right=b.width-20,top=b.mobile&&inspectorOpen?18:125,bottom=b.height-60,px=Math.min(108*zoom,(right-left)/2),py=Math.min(65*zoom,(bottom-top)/2);
  const tx=center?(left+right)/2:Math.max(left+px,Math.min(right-px,cx)),ty=center?(top+bottom)/2:Math.max(top+py,Math.min(bottom-py,cy));
  if(zoom!==v.zoom||Math.abs(tx-cx)>1||Math.abs(ty-cy)>1)void flow.setViewport({zoom,x:tx-(p.x+98)*zoom,y:ty-(p.y+56)*zoom},{duration});else void flow.setViewport(v,{duration:0});
 }
 useEffect(()=>{onViewportReader(()=>flow.getViewport());},[flow,onViewportReader]);
 useEffect(()=>{const timer=setTimeout(()=>{if(!container.current?.clientWidth)return;fit([...mapIds],0);mounted.current=true;},80);return ()=>clearTimeout(timer);},[flow]);
 useEffect(()=>{if(!mounted.current)return;const duration=matchMedia('(prefers-reduced-motion: reduce)').matches?0:320;if(camera.kind==='restore'&&camera.viewport)void flow.setViewport(camera.viewport,{duration});else if(camera.kind==='all')fit([...mapIds],duration);else if(camera.kind==='focus'&&selected)fit([...(gravity?gravityMembers(selected,context.route,trace,contextAnchor):visibleRelated(selected,false,context.route,contextAnchor))],duration,!gravity);else if(camera.kind==='ensure')ensure(duration);},[camera.id]);
 return <div ref={container} className={`network-canvas ${zoom<.48?'map-overview':'map-detail'} ${gravity?'gravity-active':''}`} aria-label="Statistikatlas – gesamte interaktive Netzkarte"><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} minZoom={.05} maxZoom={1.5} nodesConnectable={false} nodesDraggable={true} onNodeDrag={(_,node)=>setDragged({id:node.id,position:node.position})} onNodeDragStop={(_,node)=>{setDragged(null);handlers.current.onLayoutChange?.(dragLayout(node.id,node.position,positions,selected,context.route));}} elementsSelectable={false} onEdgeMouseEnter={(_,edge)=>setEdgeHover(edge.id)} onEdgeMouseLeave={()=>setEdgeHover(null)} onPaneClick={onBackground} onMoveEnd={(_,v)=>onViewport(v)} onEdgeClick={(_,e)=>onSelect(referenceInMap(e.source===focus?.id?e.target:e.source,mapReference,context.route,contextAnchor))} onlyRenderVisibleElements zoomOnDoubleClick={false} ariaLabelConfig={{'controls.zoomIn.ariaLabel':'Karte vergrößern','controls.zoomOut.ariaLabel':'Karte verkleinern','controls.fitView.ariaLabel':'Ganze Karte zeigen'}}><Background color="#cdd4c3" gap={24} size={1}/><Controls showInteractive={false} showFitView={false}/><MiniMap nodeColor={n=>n.type==='region'?'transparent':n.id===selected?.id?'#8b2e2e':hoverNeighbors?.has(n.id)?'#7a8f6e':'#bcc8b1'} maskColor="rgba(250,248,243,.8)" pannable zoomable ariaLabel="Orientierung in der gesamten Karte"/></ReactFlow></div>;
}
