import { useRef } from 'react';
import { distributionGroups } from '../domain/descriptive';
import { formatValue, quantitative, fitColumnValue, validColumnValue, type SurveyColumn } from '../domain/survey';
import { numberText, indexFor, valuesFor, valueFor, outputRef, contextFor, rankContext, unitFor, type LessonContext, type Ref, type Variable } from '../domain/learning';
import type { DataPair } from '../domain/statistics';
import { SurveyValueInput } from './SurveyData';
function Distribution({values,c,column,onCase,label}:{values:(number|null)[];c:LessonContext;column?:SurveyColumn;onCase:(id:string)=>void;label:string}){
 if(values.some(n=>n===null))return <p className="small-copy">Diese Darstellung ist bei den aktuellen Daten nicht definiert.</p>;
 const groups=distributionGroups(values as number[],column),max=Math.max(1,...groups.map(g=>g.count)),step=330/Math.max(groups.length,1),selected=indexFor(c);
 return <div className="survey-distribution"><svg className="survey-plot" viewBox="0 0 400 224" role="group" aria-label={label}><text x={36} y={18} className="chart-label">Befragte pro Kategorie / Klasse</text><line x1={34} x2={374} y1={182} y2={182} className="chart-axis"/>{groups.map((g,i)=>{const active=g.indices.includes(selected),height=g.count/max*132,x=38+i*step;return <g key={g.key} role="button" tabIndex={active?0:-1} aria-label={`${g.label}: ${g.count} Befragte`} onClick={()=>{if(g.indices.length){const k=g.indices.indexOf(selected);onCase(c.pairs[g.indices[(k+1)%g.indices.length]].id);}}} onKeyDown={e=>{if((e.key==='Enter'||e.key===' ')&&g.indices.length){e.preventDefault();onCase(c.pairs[g.indices[(g.indices.indexOf(selected)+1)%g.indices.length]].id);}}} className={`chart-bar ${active?'selected':''}`}><rect x={x} y={32} width={Math.max(1,step-4)} height={154} fill="transparent"/><rect x={x} y={182-height} width={Math.max(1,step-4)} height={height} className="bar-mark"/><text x={x+(step-4)/2} y={176-height} textAnchor="middle" className="chart-label">{g.count}</text></g>;})}<text x={37} y={205} className="chart-label">{column?.categories?'Kategorien in Codebuch-Reihenfolge':numberText(Math.min(...values as number[]),1)}</text>{!column?.categories&&<text x={370} y={205} className="chart-label" textAnchor="end">{numberText(Math.max(...values as number[]),1)}</text>}</svg><p className="small-copy">{c.caseId}: {column?formatValue(column,values[selected]):numberText(values[selected])}{column?.unit?' '+column.unit:''}. Die markierte Gruppe enthält diese Person. Ein Klick wechselt durch die Personen derselben Gruppe.</p></div>;
}
function Scatter({c,onCase,onPairs,readOnly=false}:{c:LessonContext;onCase:(id:string)=>void;onPairs:(pairs:DataPair[])=>void;readOnly?:boolean}){
 const drag=useRef<{id:string;x:[number,number];y:[number,number]}|null>(null),columns=c.columns!,domain=(v:Variable):[number,number]=>{const values=c.pairs.map(p=>p[v]),min=Math.min(...values),max=Math.max(...values),pad=Math.max((max-min)*.1,columns[v].step||.1);return [min-pad,max+pad];},xd=domain('x'),yd=domain('y'),px=(x:number)=>46+(x-xd[0])/(xd[1]-xd[0])*310,py=(y:number)=>207-(y-yd[0])/(yd[1]-yd[0])*166;
 function update(id:string,x:number,y:number){onPairs(c.pairs.map(p=>p.id===id?{...p,x:Number(fitColumnValue(columns.x,x).toFixed(6)),y:Number(fitColumnValue(columns.y,y).toFixed(6))}:p));}
 const points=[...c.pairs.filter(p=>p.id!==c.caseId),...c.pairs.filter(p=>p.id===c.caseId)],active=c.pairs[indexFor(c)];
 return <div><svg className="survey-plot survey-scatter" viewBox="0 0 400 250" role="group" aria-label={`Streudiagramm: ${columns.x.title} und ${columns.y.title}`} onPointerMove={e=>{const d=drag.current,m=e.currentTarget.getScreenCTM();if(!d||!m)return;const p=e.currentTarget.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const q=p.matrixTransform(m.inverse());update(d.id,d.x[0]+(q.x-46)/310*(d.x[1]-d.x[0]),d.y[0]+(207-q.y)/166*(d.y[1]-d.y[0]));}} onPointerUp={e=>{drag.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}} onPointerCancel={()=>{drag.current=null;}}><line x1={46} x2={360} y1={210} y2={210} className="chart-axis"/><line x1={43} x2={43} y1={38} y2={210} className="chart-axis"/>{[0,.5,1].map(t=><g key={t}><text x={46+310*t} y={230} textAnchor="middle" className="chart-label">{numberText(xd[0]+(xd[1]-xd[0])*t,1)}</text><text x={37} y={210-166*t} textAnchor="end" className="chart-label">{numberText(yd[0]+(yd[1]-yd[0])*t,1)}</text></g>)}{c.stats.meanX!==null&&c.stats.meanY!==null&&<><line x1={px(c.stats.meanX)} x2={px(c.stats.meanX)} y1={38} y2={210} className="mean-line"/><line x1={43} x2={360} y1={py(c.stats.meanY)} y2={py(c.stats.meanY)} className="mean-line"/></>}{points.map((p,i)=>{const selected=p.id===c.caseId,x=px(p.x)+(columns.x.categories?(i%5-2)*1.1:0),y=py(p.y)+(columns.y.categories?(i%7-3)*.8:0);return <g key={p.id} role="button" tabIndex={selected?0:-1} className={`chart-point ${selected?'selected':''}`} aria-label={`${p.id}: ${formatValue(columns.x,p.x)} und ${formatValue(columns.y,p.y)}`} onClick={()=>onCase(p.id)} onPointerDown={e=>{onCase(p.id);if(readOnly)return;drag.current={id:p.id,x:xd,y:yd};e.currentTarget.ownerSVGElement?.setPointerCapture(e.pointerId);}} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)&&!readOnly){e.preventDefault();update(p.id,p.x+(e.key==='ArrowRight'?columns.x.step:e.key==='ArrowLeft'?-columns.x.step:0),p.y+(e.key==='ArrowUp'?columns.y.step:e.key==='ArrowDown'?-columns.y.step:0));}}}><circle cx={x} cy={y} r={selected?9:5} fill="transparent"/><circle cx={x} cy={y} r={selected?5.5:2.7} className="point-mark" opacity={selected?1:.5}/>{selected&&<text x={x+8} y={y-9} className="chart-label">{p.id}</text>}</g>;})}</svg><p className="small-copy">X: {columns.x.title} {columns.x.unit&&`(${columns.x.unit})`}<br/>Y: {columns.y.title} {columns.y.unit&&`(${columns.y.unit})`}</p><p className="small-copy">{c.caseId}: ({numberText(active?.x)}; {numberText(active?.y)}). {readOnly?'Ränge werden aus den Originalantworten berechnet.':'Punkte ziehen oder die ausgewählte Person mit Pfeiltasten verändern; Werte rasten auf zulässigen Stufen ein.'}{(columns.x.categories||columns.y.categories)&&' Kategorienpunkte sind für die Sichtbarkeit leicht versetzt; die Berechnung verwendet unveränderte Antworten.'}</p></div>;
}
export function SurveyExperiment({reference:r,context:raw,onPairs,onCase,onData,onReset}:{reference:Ref;context:LessonContext;onPairs:(pairs:DataPair[])=>void;onCase:(id:string)=>void;onData:()=>void;onReset:()=>void}){
 const out=outputRef(r),c=out.id==='spearman'?rankContext(raw):contextFor(r,raw),v=r.variable,col=c.columns![v],both=['pairs','crossproduct','crossproduct_sum','covariance','sd_product','pearson','spearman','crosstab','linear'].includes(out.id),scatter=both&&!['crosstab','crossproduct_sum'].includes(out.id)&&quantitative(c.columns!.x,c.likertMetric)&&quantitative(c.columns!.y,c.likertMetric),readOnly=!!c.isRanked;
 const mode=['ss','variance','sd','squared_deviation'].includes(out.id)?'squared_deviation':['deviation','centering'].includes(out.id)?'deviation':out.id==='z'?'z':out.id==='crossproduct_sum'?out.use==='z'?'zproducts':'crossproduct':out.id==='ranks'?'ranks':'series';
 const values=mode==='ranks'?rankContext(raw).pairs.map(p=>p[v]):mode==='series'?c.pairs.map(p=>p[v]):valuesFor(mode,v,c),transformed=mode!=='series',mean=v==='x'?c.stats.meanX:c.stats.meanY,editable=!readOnly&&!col.categories;
 function change(axis:Variable,n:number){onPairs(raw.pairs.map(p=>p.id===raw.caseId?{...p,[axis]:n}:p));}
 function transform(kind:'shift'|'constant'|'curve'){if(kind==='curve'){const xs=raw.pairs.map(p=>p.x),min=Math.min(...xs),range=Math.max(...xs)-min||1,ys=raw.pairs.map(p=>p.y),low=Math.min(...ys),span=Math.max(...ys)-low;onPairs(raw.pairs.map(p=>({...p,y:Number(fitColumnValue(raw.columns!.y,low+span*((p.x-min)/range*2-1)**2).toFixed(6))})));return;}if(mean===null)return;onPairs(raw.pairs.map(p=>({...p,[v]:Number((kind==='shift'?p[v]+1:mean).toFixed(6))})));}
 return <section className="survey-experiment"><h2>{scatter?'Alle Befragten im Zusammenhang':transformed?'Wie verteilen sich die Rechenbeiträge?':'Die Verteilung erkunden'}</h2>{scatter?<Scatter c={c} onCase={onCase} onPairs={onPairs} readOnly={readOnly}/>:<Distribution values={values} c={c} column={transformed?undefined:col} onCase={onCase} label={transformed?'Verteilung der Beiträge aller Befragten':`Verteilung: ${col.title}`}/>}<p className="small-copy">{transformed?`Die Darstellung fasst alle ${c.pairs.length} ${mode==='squared_deviation'?'quadrierten Abweichungen':mode==='deviation'?'Abweichungen':mode==='z'?'z-Werte':mode==='ranks'?'Ränge':'Produkte'} zusammen. Der Beitrag der ausgewählten Person ist in ihrer Formel nachvollziehbar.`:`Alle ${c.pairs.length} Befragten gehen in die Rechnung ein.`}</p>{editable&&<div className="experiment-actions"><button disabled={!raw.pairs.every(p=>validColumnValue(col,p[v]+1))} onClick={()=>transform('shift')}>Alle {v.toUpperCase()} + 1</button><button disabled={mean===null||!validColumnValue(col,mean)} onClick={()=>transform('constant')}>{v.toUpperCase()} konstant setzen</button>{both&&!raw.columns!.x.categories&&!raw.columns!.y.categories&&<button onClick={()=>transform('curve')}>Gekrümmtes Muster</button>}</div>}<div className="respondent-editor"><div><strong>{raw.caseId} bearbeiten</strong><button onClick={onData}>Im Datensatz ansehen →</button></div>{(both?['x','y'] as Variable[]:[v]).map(axis=><label key={axis}><span>{axis.toUpperCase()} · {raw.columns![axis].title}</span><SurveyValueInput key={`${raw.caseId}-${raw.columns![axis].id}`} column={raw.columns![axis]} value={raw.pairs[indexFor(raw)][axis]} label={`${raw.caseId}: ${raw.columns![axis].title}`} onChange={n=>change(axis,n)}/></label>)}<p className="small-copy">Geändert werden die Originalantworten dieser Person. Ränge, Formeln und alle Verfahren werden daraus neu berechnet.</p><button className="text-button" onClick={onReset}>Ausgangsdaten wiederherstellen</button></div>{out.id==='scaling'&&<p className="small-copy">Skalierter Wert: {numberText(valueFor(r,raw))} {unitFor(r,raw)}. {r.use==='z'?'Vorher wurde der Mittelwert abgezogen.':'Hier wird der ursprüngliche Wert geteilt.'}</p>}</section>;
}
