import { useEffect, useState } from 'react';
import { crossTable, distributionGroups, averageRanks, middleValues } from '../domain/descriptive';
import { formatValue } from '../domain/survey';
import { numberText, indexFor, ref, type Ref, type LessonContext } from '../domain/learning';
export function SurveyAnalysis({reference:r,context:c,onCase,onSelect}:{reference:Ref;context:LessonContext;onCase:(id:string)=>void;onSelect:(r:Ref)=>void}){
 const [percent,setPercent]=useState<'count'|'row'|'all'>('count'),[page,setPage]=useState(0),v=r.variable,index=indexFor(c),col=c.columns?.[v];
 useEffect(()=>setPage(Math.floor(index/10)),[c.caseId]);
 const selectGroup=(indices:number[])=>{if(!indices.length)return;const current=indices.indexOf(index);onCase(c.pairs[indices[(current+1)%indices.length]].id);};
 if(r.id==='frequency'){const groups=distributionGroups(c.pairs.map(p=>p[v]),col);return <section className="analysis-results"><h2>Die Verteilung von {col?.title||v.toUpperCase()}</h2>{!col?.categories&&groups.some(g=>g.key.startsWith('bin'))&&<p className="small-copy">Alle {c.pairs.length} Werte in zehn gleich breiten Klassen. Die letzte Klasse schließt die Obergrenze ein.</p>}<table className="analysis-table"><thead><tr><th>Ausprägung / Klasse</th><th>Anzahl</th><th>Anteil</th></tr></thead><tbody>{groups.map(g=><tr key={g.key} className={g.indices.includes(index)?'selected':''}><th><button disabled={!g.count} onClick={()=>selectGroup(g.indices)}>{g.label}</button></th><td>{g.count}</td><td>{numberText(g.proportion*100,1)} %</td></tr>)}</tbody><tfoot><tr><th>Gesamt</th><td>{c.pairs.length}</td><td>100 %</td></tr></tfoot></table><p className="small-copy">Eine Kategorie anklicken, um einen zugehörigen Fall auszuwählen. Erneutes Klicken wechselt innerhalb dieser Gruppe weiter.</p></section>;}
 if(r.id==='crosstab'){const t=crossTable(c.pairs,c.columns?.x.categories?.map(k=>k.value),c.columns?.y.categories?.map(k=>k.value));return <section className="analysis-results"><h2>{c.columns?.x.title} × {c.columns?.y.title}</h2><label className="table-mode">Zellen zeigen<select value={percent} onChange={e=>setPercent(e.target.value as typeof percent)}><option value="count">Absolute Häufigkeiten</option><option value="row">Zeilenprozente</option><option value="all">Prozent aller Befragten</option></select></label><div className="cross-table-scroll"><table className="analysis-table"><thead><tr><th>X ↓ / Y →</th>{t.y.map(y=><th key={y}>{formatValue(c.columns?.y,y)}</th>)}<th>n der Zeile</th></tr></thead><tbody>{t.x.map((x,i)=><tr key={x}><th>{formatValue(c.columns?.x,x)}</th>{t.y.map((y,j)=>{const count=t.cells[i][j],indices=c.pairs.flatMap((p,k)=>p.x===x&&p.y===y?[k]:[]);return <td key={y} className={indices.includes(index)?'selected':''}><button disabled={!count} onClick={()=>selectGroup(indices)} aria-label={`${formatValue(c.columns?.x,x)} und ${formatValue(c.columns?.y,y)}: ${count} Befragte`}>{percent==='count'?count:percent==='row'?!t.rowTotals[i]?'—':`${numberText(count/t.rowTotals[i]*100,1)} %`:`${numberText(count/t.n*100,1)} %`}</button></td>;})}<td>{t.rowTotals[i]}</td></tr>)}</tbody><tfoot><tr><th>n der Spalte</th>{t.columnTotals.map((n,j)=><td key={j}>{n}</td>)}<td>{t.n}</td></tr></tfoot></table></div><p className="small-copy">Zeilenprozente teilen jede Zelle durch die Zahl der Befragten in ihrer X-Gruppe. Zellen anklicken, um passende Personen zu erkunden.</p></section>;}
 if(r.id==='median'){const m=middleValues(c.pairs.map(p=>p[v]));if(!m)return null;return <div className="median-result"><span>Mittlere Positionen {Math.floor((c.pairs.length+1)/2)} und {Math.ceil((c.pairs.length+1)/2)}</span><strong>{formatValue(col,m[0])}{m[0]!==m[1]&&<> &amp; {formatValue(col,m[1])}</>}</strong><button onClick={()=>onSelect(ref('ranks',v))}>Wie entsteht diese Reihenfolge? →</button></div>;}
 if(r.id==='ranks'){const ranks=averageRanks(c.pairs.map(p=>p[v])),visible=c.pairs.slice(page*10,page*10+10);return <section className="analysis-results"><h2>Werte und mittlere Ränge</h2><table className="analysis-table"><thead><tr><th>Befragte</th><th>Antwort</th><th>Rang</th></tr></thead><tbody>{visible.map((p,i)=><tr key={p.id} className={p.id===c.caseId?'selected':''}><th><button onClick={()=>onCase(p.id)}>{p.id}</button></th><td>{formatValue(col,p[v])}</td><td>{numberText(ranks[page*10+i])}</td></tr>)}</tbody></table><div className="survey-pagination"><button disabled={!page} onClick={()=>setPage(page-1)}>←</button><span>Seite {page+1} von {Math.ceil(c.pairs.length/10)}</span><button disabled={(page+1)*10>=c.pairs.length} onClick={()=>setPage(page+1)}>→</button></div></section>;}
 return null;
}
