import { memo,useCallback,useEffect,useMemo,useRef,useState,type ComponentProps,type CSSProperties } from 'react';
import { ReactFlow,Controls,MiniMap,Handle,Position,MarkerType,useReactFlow,type NodeProps,type Node,type Viewport } from '@xyflow/react';
import { conceptById,concepts } from '../../domain/concepts';
import { titleFor,displayValue,valueFor,unitFor,type Ref } from '../../domain/learning';
import { mapRelations,referenceInMap,routeAfterSelection,regionConcepts } from '../../domain/network';
import { restingPlaces,topicAreas } from '../../domain/mapLayout';
import { detailLevel,arrangeOverviewLabels,orientationPoints,focusPath,overviewEdges,type DetailLevel,type FocusMode } from '../../domain/prototypeMap';
import type { NetworkMap } from '../NetworkMap';

type Props=ComponentProps<typeof NetworkMap>&{previewOpen?:boolean;focusMode?:FocusMode;guidePath?:readonly string[]};
type CardData={reference:Ref;title:string;note:string;value:string;level:DetailLevel;active:boolean;related:boolean;hovered:boolean;visited:boolean;caption?:{dx:number;dy:number};onSelect:(r:Ref)=>void;onHover:(id:string|null)=>void};
export const ExplorerNode=memo(function ExplorerNode({data:d}:NodeProps<Node<CardData,'explorer'>>){
 const landmark=orientationPoints.has(d.reference.id),label=d.level!=='overview'||!!d.caption;
 return <div className={`explorer-node level-${d.level} ${d.active?'is-selected':''} ${d.hovered?'is-hovered':''} ${d.related?'is-related':'is-dimmed'} ${landmark?'is-landmark':''}`}>
 <Handle type="target" position={Position.Left}/><button className="nodrag" onClick={()=>d.onSelect(d.reference)} onPointerEnter={e=>{if(e.pointerType!=='touch')d.onHover(d.reference.id);}} onPointerLeave={()=>d.onHover(null)} onFocus={()=>d.onHover(d.reference.id)} onBlur={()=>d.onHover(null)} aria-label={`${d.title} erkunden`} aria-pressed={d.active} title={d.title}>
 <i className={`explorer-dot ${d.visited?'is-visited':''}`} aria-hidden="true"/>{d.level==='overview'&&d.caption&&<i className="explorer-label-line" aria-hidden="true" style={{top:`calc(50% + ${d.caption.dy>=0?6:d.caption.dy+54}px * var(--map-inverse))`,height:`calc(${Math.max(0,d.caption.dy>=0?d.caption.dy-6:-d.caption.dy-60)}px * var(--map-inverse))`}}/>}{label&&<strong style={d.level==='overview'&&d.caption?{left:`calc(50% + ${d.caption.dx}px * var(--map-inverse))`,top:`calc(50% + ${d.caption.dy}px * var(--map-inverse))`}:undefined}>{d.title}</strong>}{d.level==='detail'&&<><small>{d.value||d.note}</small><span className="explorer-node-kind">{conceptById[d.reference.id].category==='operation'?'Rechenschritt':'Baustein'}</span></>}
 </button><Handle type="source" position={Position.Right}/></div>;
},(a,b)=>{const x=a.data,y=b.data;return x.title===y.title&&x.note===y.note&&x.value===y.value&&x.level===y.level&&x.active===y.active&&x.related===y.related&&x.hovered===y.hovered&&x.visited===y.visited&&x.caption?.dx===y.caption?.dx&&x.caption?.dy===y.caption?.dy&&x.reference.id===y.reference.id&&x.reference.use===y.reference.use&&x.reference.variable===y.reference.variable&&x.reference.basis===y.reference.basis&&x.onSelect===y.onSelect&&x.onHover===y.onHover;});
type Area=ReturnType<typeof topicAreas>[number];
const areaTitles:Record<string,string>={basics:'Kennwerte',prepare:'Daten vorbereiten',inference:'Statistische Schlüsse',groups:'Gruppen vergleichen',models:'Modelle & Vorhersagen',categorical:'Kategorien & Ränge',describe:'Daten beschreiben',scales:'Items & Skalen',probability_foundations:'Zufall & Verteilungen',inference_foundations:'Schätzen & Testen',model_foundations:'Modelle beurteilen',measurement_foundations:'Messung verstehen'};
const shortAreas:Record<string,string>={basics:'Kennwerte',prepare:'Daten',inference:'Schlüsse',groups:'Gruppen',models:'Modelle',categorical:'Kategorien',describe:'Beschreiben',scales:'Skalen',probability_foundations:'Zufall',inference_foundations:'Schätzen',model_foundations:'Modellprüfung',measurement_foundations:'Messung'};
const ExplorerArea=memo(function ExplorerArea({data:d}:NodeProps<Node<{area:Area;labelVisible:boolean;short:boolean;onOpen:(id:string)=>void},'explorer-area'>>){return <div className="explorer-area" style={{width:d.area.width,height:d.area.height}}><button className={`nodrag ${d.labelVisible?'':'area-marker'}`} title={d.area.title} style={{left:d.area.labelX-d.area.x,top:d.area.labelY-d.area.y,maxWidth:`max(48px, calc(${d.area.width}px / var(--map-inverse) - 18px))`}} onClick={()=>d.onOpen(d.area.id)} aria-label={`${d.area.title}: Bereich erkunden`}>{d.labelVisible?(d.short?shortAreas[d.area.id]:areaTitles[d.area.id]):''}<span aria-hidden="true"> ↗</span></button></div>;});
const nodeTypes={'explorer':ExplorerNode,'explorer-area':ExplorerArea};
const areas=topicAreas(restingPlaces);
export function ExplorationMap(p:Props){
 const ready=useRef(false),container=useRef<HTMLDivElement>(null),flow=useReactFlow(),callbacks=useRef(p);callbacks.current=p;
 const [labelZoom,setLabelZoom]=useState(.045),[level,setLevel]=useState<DetailLevel>('overview'),[hovered,setHovered]=useState<string|null>(null);
 useEffect(()=>{if(!p.hovered){setHovered(null);return;}const timer=setTimeout(()=>setHovered(p.hovered),140);return ()=>clearTimeout(timer);},[p.hovered]);
 const onSelect=useCallback((r:Ref)=>callbacks.current.onSelect(r),[]),onHover=useCallback((id:string|null)=>callbacks.current.onHover(id),[]),onArea=useCallback((id:string)=>callbacks.current.onRegion?.(id),[]);
 const updateZoom=useCallback((v:Viewport)=>{container.current?.style.setProperty('--map-inverse',String(1/v.zoom));if(v.zoom<.32)setLabelZoom(Math.max(.045,Math.floor(v.zoom*40)/40));setLevel(previous=>{const next=detailLevel(v.zoom);return next===previous?previous:next;});},[]);
 const mapReference=p.highlightRef||(hovered?referenceInMap(hovered,p.selected,p.context.route,p.contextAnchor):p.selected),route=mapReference?routeAfterSelection(p.selected,mapReference,p.context.route):p.context.route;
 const relations=useMemo(()=>mapRelations(mapReference,route,p.contextAnchor||p.selected),[mapReference?.id,mapReference?.use,mapReference?.basis,mapReference?.variable,route,p.contextAnchor,p.selected]);
 const path=useMemo(()=>{if(p.guidePath&&!hovered&&!p.highlightRef){const pairs=new Set(p.guidePath.slice(1).map((id,i)=>`${p.guidePath![i]}--${id}`)),edges=new Set(relations.filter(e=>!e.alternative&&pairs.has(e.id)).map(e=>e.id));return {nodes:new Set(p.guidePath),edges,direct:edges};}return focusPath(mapReference?.id||null,relations,p.focusMode||'near',!!hovered||!!p.highlightRef);},[mapReference?.id,relations,p.focusMode,hovered,p.highlightRef,p.guidePath]);
 const labels=useMemo(()=>arrangeOverviewLabels(labelZoom,restingPlaces,areas,p.selected?.id,hovered||undefined),[labelZoom,p.selected?.id,hovered]);
 const nodes=useMemo(()=>[
 ...areas.map(area=>({id:`region-${area.id}`,type:'explorer-area',position:{x:area.x,y:area.y},width:area.width,height:area.height,style:{pointerEvents:'none' as const},zIndex:0,draggable:false,selectable:false,data:{area,labelVisible:level!=='overview'||!!labels.regions[area.id],short:level==='overview'&&labelZoom<.09,onOpen:onArea}})),
 ...concepts.map(c=>{const reference=referenceInMap(c.id,mapReference,p.context.route,p.contextAnchor),numeric=level==='detail'?valueFor(reference,p.context):null;return {id:c.id,type:'explorer',position:restingPlaces[c.id],width:196,height:136,style:{pointerEvents:'all' as const},zIndex:2,draggable:false,selectable:false,focusable:false,data:{reference,title:titleFor(reference),note:c.short,value:numeric===null?'':`${displayValue(reference,p.context)} ${unitFor(reference,p.context)}`,level,active:p.selected?.id===c.id,related:path.nodes.has(c.id),hovered:hovered===c.id,visited:p.visited.has(c.id),caption:labels.nodes[c.id],onSelect,onHover}};})
 ],[labels,labelZoom,level,p.selected,p.context,p.contextAnchor,p.visited,mapReference?.id,mapReference?.use,mapReference?.basis,mapReference?.variable,path,hovered,onArea,onSelect,onHover]);
 const edges=useMemo(()=>{
  const skeleton=new Set(overviewEdges(relations).map(e=>e.id));
  return relations.filter(e=>level!=='overview'||path.edges.has(e.id)||skeleton.has(e.id)).map(e=>{const focused=path.edges.has(e.id),direct=focused&&path.direct.has(e.id),color=e.kind==='meaning'?'#627f94':e.kind==='condition'?'#a07042':'#346751';return {id:e.id,source:e.source,target:e.target,type:'default',focusable:false,zIndex:focused?1:0,label:level==='detail'&&direct?e.label:undefined,markerEnd:focused?{type:MarkerType.ArrowClosed,color,width:14,height:14}:undefined,style:{vectorEffect:'non-scaling-stroke' as const,stroke:color,strokeWidth:direct?2.5:focused?1.5:1,opacity:focused?(direct?1:.65):mapReference?.id?.08:level==='overview'?.18:.15,strokeDasharray:e.kind==='meaning'?'2 5':e.kind==='condition'?'6 4':e.alternative?'3 7':undefined},labelStyle:{fontSize:13,fill:'#375144'},labelBgStyle:{fill:'#faf8f3',fillOpacity:.95},interactionWidth:16};});
 },[relations,level,path,mapReference?.id]);
 function bounds(){const el=container.current,width=el?.clientWidth||1000,height=el?.clientHeight||700,mobile=width<=760,workspace=el?.parentElement,overlay=workspace?.querySelector<HTMLElement>(p.inspectorOpen?'.network-inspector':'.explorer-preview'),rect=overlay?.getBoundingClientRect(),base=el?.getBoundingClientRect();return {width:!mobile&&rect&&base?Math.max(120,rect.left-base.left-14):width,height:mobile&&rect&&base?Math.max(160,rect.top-base.top-14):height,mobile};}
 function fit(ids:string[],duration=260){const points=ids.map(id=>restingPlaces[id]).filter(Boolean);if(!points.length)return;const b=bounds(),left=Math.min(...points.map(p=>p.x))-100,right=Math.max(...points.map(p=>p.x))+296,top=Math.min(...points.map(p=>p.y))-180,bottom=Math.max(...points.map(p=>p.y))+236,zoom=Math.max(.045,Math.min(.95,(b.width-60)/(right-left),(b.height-100)/(bottom-top)));void flow.setViewport({zoom,x:b.width/2-(left+right)*zoom/2,y:b.height/2-(top+bottom)*zoom/2+10},{duration});}
 function ensure(duration:number){if(!p.selected)return;const point=restingPlaces[p.selected.id],v=flow.getViewport(),b=bounds(),cx=(point.x+98)*v.zoom+v.x,cy=(point.y+68)*v.zoom+v.y,padX=Math.min(b.width/2-10,Math.max(24,98*v.zoom+12)),padY=Math.min(b.height/2-10,Math.max(24,68*v.zoom+12)),top=p.guidePath&&b.mobile?115:16,tx=Math.max(padX,Math.min(b.width-padX,cx)),ty=Math.max(top+padY,Math.min(b.height-padY,cy));if(Math.abs(tx-cx)>1||Math.abs(ty-cy)>1)void flow.setViewport({...v,x:v.x+tx-cx,y:v.y+ty-cy},{duration});}
 useEffect(()=>{p.onViewportReader(()=>flow.getViewport());p.onLayoutReader?.(()=>restingPlaces);},[p.onViewportReader,p.onLayoutReader,flow]);
 useEffect(()=>{const timer=setTimeout(()=>{fit(concepts.map(c=>c.id),0);ready.current=true;updateZoom(flow.getViewport());},50);return ()=>clearTimeout(timer);},[flow]);
 useEffect(()=>{if(!ready.current)return;const duration=matchMedia('(prefers-reduced-motion: reduce)').matches?0:260;if(p.camera.kind==='all')fit(concepts.map(c=>c.id),duration);else if(p.camera.kind==='area'&&p.camera.regionId)fit(regionConcepts(p.camera.regionId),duration);else if(p.camera.kind==='restore'&&p.camera.viewport)void flow.setViewport(p.camera.viewport,{duration});else if(p.camera.kind==='focus'&&p.selected)fit(p.guidePath?[...p.guidePath]:[...focusPath(p.selected.id,mapRelations(p.selected,p.context.route,p.contextAnchor||p.selected),p.focusMode||'near').nodes],duration);else if(p.camera.kind==='ensure')ensure(duration);},[p.camera.id]);
 return <div ref={container} className={`network-canvas explorer-canvas explorer-${level}`} style={{'--map-inverse':6.25} as CSSProperties} aria-label="Statistikatlas – Karte mit festen Positionen und abgestuften Details"><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} minZoom={.045} maxZoom={1.5} nodesConnectable={false} nodesDraggable={false} elementsSelectable={false} onlyRenderVisibleElements onPaneClick={p.onBackground} onMove={(_,v)=>updateZoom(v)} onMoveEnd={(_,v)=>{updateZoom(v);p.onViewport(v);}} onEdgeClick={(_,edge)=>onSelect(referenceInMap(edge.source===p.selected?.id?edge.target:edge.source,mapReference,p.context.route,p.contextAnchor))} zoomOnDoubleClick={false} ariaLabelConfig={{'controls.zoomIn.ariaLabel':'Mehr Details zeigen','controls.zoomOut.ariaLabel':'Mehr Überblick zeigen'}}><Controls showInteractive={false} showFitView={false}/><MiniMap nodeColor={n=>n.type==='explorer-area'?'transparent':n.id===p.selected?.id?'#8b2e2e':'#9daf9e'} pannable zoomable maskColor="rgba(250,248,243,.75)" ariaLabel="Dein Ausschnitt in der ganzen Karte"/></ReactFlow><div className="explorer-zoom-caption" aria-live="polite">{level==='overview'?'Übersicht · Themen & Orientierungspunkte':level==='names'?'Begriffe · Zusammenhänge erkunden':'Details · Bausteine lesen'}</div></div>;
}
