import { chromium } from '/Users/yannickdiehl/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core/index.mjs';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
const url=process.argv.includes('--offline')?pathToFileURL(path.resolve('Statistikatlas-Prototyp.html')).href:'http://127.0.0.1:5173/';
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--disable-background-networking']});
const errors=[],network=[],checks=[];
const check=(name,condition)=>{assert(condition,name);checks.push(name);};
try {
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 await page.route('**/*',r=>{const u=new URL(r.request().url());if(['http:','https:'].includes(u.protocol)&&!['127.0.0.1','localhost'].includes(u.hostname)){network.push(u.href);return r.abort();}return r.continue();});
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto(url);await page.getByTestId('detail-title').waitFor();await page.waitForTimeout(600);
 check('Initialer Fokus auf z mit fünf einzelnen Knoten',await page.locator('[data-concept]').count()===5);
 check('z-Wert für Fall 2',await page.getByTestId('value-z').innerText()==='−0,632'||await page.getByTestId('value-z').innerText()==='-0,632');
 await page.getByRole('button',{name:'Standardabweichung: Bausteine aufklappen',exact:true}).click();await page.waitForTimeout(500);
 check('Aufklappen ergänzt Varianz und Quadratwurzel',await page.locator('[data-concept="variance"]').count()===1&&await page.locator('[data-concept="sqrt"]').count()===1);
 check('Gemeinsam verwendete Standardabweichung erscheint einmal',await page.locator('[data-concept="sd"]').count()===1);
 await page.getByRole('button',{name:'Formelbaustein Korrigierte Stichprobenvarianz anzeigen',exact:true}).click();
 check('Formelzeichen führt zum zugehörigen Konzept',(await page.getByTestId('detail-title').innerText()).includes('Stichprobenvarianz'));
 await page.getByRole('button',{name:'Bis zur Basis aufklappen',exact:true}).click();await page.waitForTimeout(500);
 check('Rekursive Voraussetzungen enthalten Mittelwert, Zählen und Addition',await page.locator('[data-concept="mean"]').count()===1&&await page.locator('[data-concept="count"]').count()===1&&await page.locator('[data-concept="add"]').count()===1);
 await page.getByRole('button',{name:'04 Korrelation',exact:true}).click();await page.waitForTimeout(500);
 check('Pearson zunächst ohne optionalen z-Rechenweg',await page.locator('[data-concept="pearson"]').count()===1&&await page.locator('[data-concept="z"]').count()===0);
 await page.getByLabel('Alternative Wege zeigen',{exact:true}).check();await page.waitForTimeout(500);
 check('Optionaler z-Rechenweg wird einzeln zugeschaltet',await page.locator('[data-concept="z"]').count()===1&&await page.locator('.connection-optional').count()>0);
 await page.getByRole('button',{name:'Ganzer Ausschnitt',exact:true}).click();await page.waitForTimeout(500);
 check('Alle 29 Einzelkonzepte bleiben erreichbar',await page.locator('[data-concept]').count()===29);
 const ids=await page.locator('[data-concept]').evaluateAll(nodes=>nodes.map(n=>n.dataset.concept));check('Keine doppelten Knoten',new Set(ids).size===29);
 await page.getByRole('button',{name:'Zur Fokusansicht',exact:true}).click();await page.waitForTimeout(450);
 check('Die Fokusansicht reduziert den Ausschnitt wieder',await page.locator('[data-concept]').count()<29);
 const before=await page.locator('.react-flow__viewport').getAttribute('style');await page.getByRole('button',{name:'Netz vergrößern',exact:true}).click();await page.waitForTimeout(300);
 check('Zoom bedienbar',before!==await page.locator('.react-flow__viewport').getAttribute('style'));
 await page.getByRole('button',{name:'Ausgewählten Knoten lesbar anzeigen',exact:true}).click();await page.waitForTimeout(400);
 const selectionWidth=await page.locator('[data-concept="pearson"]').evaluate(n=>n.getBoundingClientRect().width);
 check('Auswahl lesen zeigt den ausgewählten Begriff mindestens in Originalgröße',selectionWidth>=248);
 await page.getByRole('button',{name:'03 z-Standardisierung',exact:true}).click();await page.waitForTimeout(450);
 await page.getByRole('button',{name:'Formelbaustein Arithmetisches Mittel anzeigen',exact:true}).click();await page.waitForTimeout(450);
 check('Verdeckter Formelbaustein wird rekursiv sichtbar',await page.locator('[data-concept="mean"]').count()===1&&await page.getByTestId('detail-title').innerText()==='Arithmetisches Mittel');
 await page.setViewportSize({width:390,height:844});await page.reload();await page.getByTestId('detail-title').waitFor();await page.waitForTimeout(500);
 check('Kein horizontaler Seitenüberlauf auf Mobilgerät',await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 await page.getByRole('button',{name:'Eine Ebene tiefer',exact:true}).click();await page.waitForTimeout(450);
 check('Aufklappen auch mobil bedienbar',await page.locator('[data-concept]').count()>5);
 check('Keine Browserfehler',errors.length===0);check('Keine externen Anfragen',network.length===0);
 await fs.mkdir('artifacts',{recursive:true});
 const report={url,checks,errors,externalRequests:network};
 await fs.writeFile(`artifacts/graph-qa${process.argv.includes('--offline')?'-offline':''}.json`,JSON.stringify(report,null,2));
 console.log(JSON.stringify(report,null,2));
} catch(error) {console.error(JSON.stringify({errors,network,checks},null,2));throw error;}
finally {await browser.close();}
