import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, Scan, Search, X, ChevronRight, SlidersHorizontal, ChevronUp } from 'lucide-react';
import type { Viewport } from '@xyflow/react';
import { type DataPair } from './domain/statistics';
import { concepts, conceptById, connections } from './domain/concepts';
import { createSurvey, validSurvey, defaultSelection, columnById, reconcileColumns, projectPairs, updateProjectedPairs, type ColumnSelection, type SurveyRow } from './domain/survey';
import { SurveyData } from './components/SurveyData';
import { ref, keyOf, lessonContext, titleFor, outputRef, type Ref, type Route, type Variable } from './domain/learning';
import { routeAfterSelection } from './domain/network';
import { initialExploration, visit, step, type ExplorationView } from './domain/exploration';
import { NetworkMap, type CameraRequest } from './components/NetworkMap';
import { ConceptInspector } from './components/ConceptInspector';
const storageKey='statistikatlas.survey.v1';
function storedStudy():{rows:SurveyRow[];selection:ColumnSelection}{try{const value=JSON.parse(localStorage.getItem(storageKey)||'null');if(validSurvey(value?.rows)){const s=value.selection;return {rows:value.rows,selection:s&&columnById[s.x]&&columnById[s.y]&&typeof s.likertMetric==='boolean'?reconcileColumns('series',s):{...defaultSelection}};}}catch{}return {rows:createSurvey(),selection:{...defaultSelection}};}

export default function App(){
 const [survey,setSurvey]=useState(()=>storedStudy().rows),[history,setHistory]=useState(()=>initialExploration(survey[1].id,storedStudy().selection)),[dataOpen,setDataOpen]=useState(false),[columnNotice,setColumnNotice]=useState(''),[highlight,setHighlight]=useState<string|null>(null),[hovered,setHovered]=useState<string|null>(null),[query,setQuery]=useState(''),[searchOpen,setSearchOpen]=useState(false),[experimentOpen,setExperimentOpen]=useState(false),[experimentRequest,setExperimentRequest]=useState(0),[invitationOpen,setInvitationOpen]=useState(true),[resetRevision,setResetRevision]=useState(0),[storageError,setStorageError]=useState(false),[camera,setCamera]=useState<CameraRequest>({id:0,kind:'all'});
 const view=history.present,selected=view.selected,viewport=useRef<Viewport|undefined>(undefined),viewportReader=useRef<(()=>Viewport)|undefined>(undefined),searchInput=useRef<HTMLInputElement>(null);
 const selection=view.columns,pairs=useMemo(()=>projectPairs(survey,selection),[survey,selection]),context=useMemo(()=>lessonContext(pairs,view.caseId,view.route,{x:columnById[selection.x],y:columnById[selection.y]},selection.likertMetric),[pairs,view.caseId,view.route,selection]);
 const visited=useMemo(()=>new Set([...history.past,view,...history.future].flatMap(v=>v.selected?[v.selected.id]:[])),[history]);
 const recent=history.past.filter(v=>v.selected).slice(-4),matches=concepts.filter(c=>`${titleFor(ref(c.id))} ${c.title} ${c.short}`.toLocaleLowerCase('de').includes(query.toLocaleLowerCase('de')));
 useEffect(()=>{try{localStorage.setItem(storageKey,JSON.stringify({rows:survey,selection}));setStorageError(false);}catch{setStorageError(true);}},[survey,selection]);
 useEffect(()=>{function key(e:KeyboardEvent){if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();searchInput.current?.focus();setSearchOpen(true);}if(e.key==='Escape'&&!dataOpen){if(searchOpen){setSearchOpen(false);searchInput.current?.blur();}else setHistory(h=>({...h,present:{...h.present,panelOpen:false}}));}}window.addEventListener('keydown',key);return ()=>window.removeEventListener('keydown',key);},[searchOpen,dataOpen]);
 function changeView(next:ExplorationView,kind:CameraRequest['kind']='ensure'){setHistory(h=>visit(h,next,viewportReader.current?.()||viewport.current));setHighlight(null);setHovered(null);setCamera(c=>({id:c.id+1,kind}));}
 function select(r:Ref,caseId?:string){if(!conceptById[r.id])return;const columns=reconcileColumns(r.basis==='ranks'?'spearman':outputRef(r).id,selection);setColumnNotice(columns.x!==selection.x||columns.y!==selection.y?`Passende Spalten eingesetzt: X = ${columnById[columns.x].title}, Y = ${columnById[columns.y].title}.`:'');setQuery('');setSearchOpen(false);if(selected&&keyOf(selected)===keyOf(r)&&selected.variable===r.variable&&(!caseId||caseId===view.caseId)){setHistory(h=>({...h,present:{...h.present,panelOpen:true}}));setCamera(c=>({id:c.id+1,kind:'ensure'}));return;}changeView({...view,selected:r,columns,variable:r.variable,route:routeAfterSelection(selected,r,view.route),caseId:caseId||view.caseId,panelOpen:true});}
 function travel(direction:'back'|'forward'){const next=step(history,direction,viewportReader.current?.()||viewport.current,pairs.map(p=>p.id));setHistory(next);setHighlight(null);setHovered(null);setCamera(c=>({id:c.id+1,kind:'restore',viewport:next.present.viewport}));}
 function wholeMap(){changeView({...view,selected:null,trace:false,panelOpen:false},'all');}
 function changePairs(next:DataPair[]){setSurvey(rows=>updateProjectedPairs(rows,selection,next));}
 function changeColumns(next:ColumnSelection){const id=selected?.basis==='ranks'?'spearman':selected?outputRef(selected).id:'series',columns=reconcileColumns(id,next);setColumnNotice(columns.x!==next.x||columns.y!==next.y?'Für diese Rechnung wurden passende Spalten eingesetzt.':'');changeView({...view,columns},'none');}
 function resetSurvey(){setResetRevision(n=>n+1);setSurvey(createSurvey());}

 function changeVariable(variable:Variable){if(!selected||selected.variable===variable)return;select({...selected,variable});}
 function changeRoute(route:Route){if(route===view.route)return;changeView({...view,route},'none');}
 function data(){setDataOpen(true);}
 const hoverConcept=highlight?.split(':')[0]||hovered,parts=highlight?.split(':'),highlightRef=parts?ref(parts[0],parts[1]==='y'?'y':parts[1]==='x'?'x':view.variable,parts[2]||undefined,parts[3]==='ranks'?'ranks':undefined):undefined;
 return <div className={`network-app ${selected?'has-selection':''} ${selected&&view.panelOpen?'has-inspector':''}`}><a className="skip-link" href={selected?'#inspector-title':'#network-search'}>Zur Begriffsauswahl springen</a>
  <header className="network-header"><strong>Statistikatlas<span>.</span></strong><span>Statistik hängt zusammen.</span><div className="network-search"><Search size={16}/><input id="network-search" ref={searchInput} type="search" aria-label="Begriff im Netzwerk finden" placeholder="Begriff finden …" value={query} onFocus={()=>setSearchOpen(true)} onChange={e=>{setQuery(e.target.value);setSearchOpen(true);}} onKeyDown={e=>{if(e.key==='Enter'&&matches[0]){e.preventDefault();select(ref(matches[0].id,view.variable));}}} aria-expanded={searchOpen} aria-controls="search-results"/>{query&&<button onClick={()=>setQuery('')} aria-label="Suche leeren"><X size={14}/></button>}{searchOpen&&<div className="network-search-results" id="search-results"><div className="search-result-caption"><span>{query?`${matches.length} passende Begriffe`:`Alle ${concepts.length} Begriffe`}</span><button onClick={()=>setSearchOpen(false)} aria-label="Suchergebnisse schließen"><X size={14}/></button></div>{matches.map(c=><button key={c.id} onClick={()=>select(ref(c.id,view.variable))} onFocus={()=>setHovered(c.id)} onBlur={()=>setHovered(null)} onPointerEnter={()=>setHovered(c.id)} onPointerLeave={()=>setHovered(null)}><strong>{titleFor(ref(c.id))}</strong><small>{c.short}</small></button>)}{!matches.length&&<p>Kein Begriff gefunden.</p>}</div>}</div></header>
  <nav className="network-toolbar" aria-label="In der Karte navigieren"><div className="history-controls"><button aria-label="Vorherige Ansicht" disabled={!history.past.length} onClick={()=>travel('back')}><ArrowLeft size={17}/></button><button aria-label="Nächste Ansicht" disabled={!history.future.length} onClick={()=>travel('forward')}><ArrowRight size={17}/></button></div><button className="whole-map-button" onClick={wholeMap}><Scan size={16}/>Ganze Karte</button><div className="exploration-trail" aria-label="Zuletzt erkundet"><span>Dein Weg</span>{recent.map((v,i)=><span className="trail-item" key={`${keyOf(v.selected!)}-${i}`}><button onClick={()=>select(v.selected!)} onPointerEnter={()=>setHovered(v.selected!.id)} onPointerLeave={()=>setHovered(null)}>{titleFor(v.selected!)}</button><ChevronRight size={12}/></span>)}<strong>{selected?titleFor(selected):'Die ganze Karte'}</strong></div><button aria-label="Datensatz mit 200 Befragten öffnen" className="network-data-button" onClick={data}><SlidersHorizontal size={15}/><span>Datensatz · 200</span></button></nav>
  <main className="network-workspace"><NetworkMap selected={selected} context={context} hovered={hoverConcept} visited={visited} onSelect={select} onHover={setHovered} onViewport={v=>{viewport.current=v;}} onViewportReader={read=>{viewportReader.current=read;}} camera={camera} trace={view.trace} inspectorOpen={view.panelOpen} highlightRef={highlightRef} onBackground={()=>setSearchOpen(false)}/>
   {!selected&&invitationOpen&&<section className="map-invitation"><button className="invitation-close" aria-label="Einführung schließen" onClick={()=>setInvitationOpen(false)}><X size={16}/></button><span className="eyebrow">Ein Netz. Viele Wege.</span><h1>Wo möchtest du anfangen?</h1><p>Klicke einen Begriff an. Folge seinen Voraussetzungen – oder entdecke, was daraus entsteht.</p><p className="small-copy">Ziehen bewegt die Karte. Zoomen bringt die Bausteine näher.</p></section>}
   {selected&&view.panelOpen&&<ConceptInspector selected={selected} context={context} selection={selection} onColumns={changeColumns} columnNotice={columnNotice} onData={data} highlight={highlight} onHighlight={setHighlight} onSelect={select} onHover={setHovered} onClose={()=>setHistory(h=>({...h,present:{...h.present,panelOpen:false}}))} onFocusMap={()=>setCamera(c=>({id:c.id+1,kind:'focus'}))} onCase={caseId=>setHistory(h=>({...h,present:{...h.present,caseId}}))} onPairs={changePairs} onReset={resetSurvey} resetRevision={resetRevision} onVariable={changeVariable} onRoute={changeRoute} trace={view.trace} onTrace={()=>setHistory(h=>({...h,present:{...h.present,trace:!h.present.trace}}))} onExperimentFocused={()=>setExperimentRequest(0)} experimentRequest={experimentRequest} experimentOpen={experimentOpen} onExperiment={setExperimentOpen}/>}
   {selected&&!view.panelOpen&&<button className="reopen-inspector" onClick={()=>{setHistory(h=>({...h,present:{...h.present,panelOpen:true}}));setCamera(c=>({id:c.id+1,kind:'ensure'}));}}>{titleFor(selected)}<ChevronUp size={17}/><span>Erklärung öffnen</span></button>}
   <div className="network-map-note" aria-live="polite">{selected?<><span className="selected-dot"/>{view.trace?'Voraussetzungen werden verfolgt':'Direkte Bezüge hervorgehoben'}<button onClick={wholeMap}>Auswahl lösen</button></>:<><span>{concepts.length} Bausteine</span><span>{connections.length} Grundbeziehungen</span></>}</div>
  </main>{dataOpen&&<SurveyData rows={survey} selection={selection} caseId={view.caseId} procedure={selected?.basis==='ranks'?'spearman':selected?outputRef(selected).id:'series'} onCase={caseId=>setHistory(h=>({...h,present:{...h.present,caseId}}))} onChange={rows=>{if(validSurvey(rows))setSurvey(rows);}} onSelection={changeColumns} onReset={resetSurvey} onClose={()=>setDataOpen(false)}/>}<footer className="network-footer"><div className="network-legend"><span><i/>Aufbau</span><span><i className="condition"/>Voraussetzung</span><span><i className="optional"/>Ergänzender Bezug</span></div>{storageError?<span role="status">Daten können gerade nur für diese Sitzung behalten werden.</span>:<span>200 synthetische Befragte · lokal gespeichert</span>}<a href={typeof location!=='undefined'&&location.protocol==='file:'?location.href:'./Statistikatlas-offline.html'} download="Statistikatlas-offline.html">Offline öffnen</a></footer>
 </div>;
}
