import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, Grid2X2, ArrowUpRight, Check, Info, CircleAlert } from 'lucide-react';
import { type Viewport } from '@xyflow/react';
import { defaultPairs, type DataPair } from './domain/statistics';
import { concepts, conceptById } from './domain/concepts';
import { validStoredPairs } from './domain/data';
import { ref, keyOf, inputs, findPath, lessonContext, titleFor, subtitle, introduction, interpretation, conditions, deepQuestions, outputRef, isOperation, numberText, valueFor, unitFor, type Ref, type Variable, type Route } from './domain/learning';
import { Formula } from './components/Formula';
import { LearningGraph } from './components/LearningGraph';
import { Experiment } from './components/Experiment';

const entries=[{id:'mean',name:'Mittelwert',question:'Wie wird aus mehreren Werten eine Zahl?'},{id:'sd',name:'Streuung',question:'Wie stark unterscheiden sich die Werte?'},{id:'z',name:'z-Standardisierung',question:'Wie weit liegt ein Wert vom Mittelwert entfernt?'},{id:'pearson',name:'Korrelation',question:'Wie hängen zwei Merkmale zusammen?'}];
type View={entry:string;focus:Ref;selected:Ref;expanded:Set<string>;route:Route;variable:Variable;caseId:string;overview:boolean;viewport?:Viewport;positions?:Map<string,{x:number;y:number}>};
const storageKey='statistikatlas.example.v2';
function readPairs():DataPair[]{try{const value:unknown=JSON.parse(localStorage.getItem(storageKey)||'null');if(validStoredPairs(value))return value;}catch{/* The example works without browser storage. */}return defaultPairs.map(p=>({...p}));}
const initial=(pairs:DataPair[]):View=>({entry:'mean',focus:ref('mean'),selected:ref('mean'),expanded:new Set([keyOf(ref('mean'))]),route:'covariance',variable:'x',caseId:pairs[Math.min(1,pairs.length-1)].id,overview:false});
const deepCopy:Record<string,string>={
 mean:'Ein einzelner großer Wert zieht den Mittelwert mit nach oben. Verändere eine Lernzeit deutlich und beobachte die gestrichelte Linie. Für geordnete Kategorien ist diese Rechnung nicht automatisch sinnvoll: Entscheidend ist, was ihre Abstände bedeuten.',
 variance:'Der Mittelwert wird aus denselben Daten geschätzt. Deshalb ergeben die Abweichungen zusammen 0: Die letzte Abweichung steht durch die übrigen bereits fest. Unter unabhängiger Zufallsziehung aus derselben Verteilung mit endlicher Varianz ist die Division durch n − 1 eine unverzerrte Schätzung der Populationsvarianz.',
 sd:'Die Varianz wird in h² beziehungsweise Aufgaben² gemessen. Die Quadratwurzel bringt die Standardabweichung zurück zu Stunden beziehungsweise Aufgaben. Sie ist kein durchschnittlicher absoluter Abstand vom Mittelwert.',
 z:'Nein. Eine z-Standardisierung verschiebt und skaliert die vorhandenen Werte. Ihre Verteilungsform bleibt erhalten. Die standardisierte Reihe hat bei s > 0 den Mittelwert 0 und die Stichproben-Standardabweichung 1. Eine Prozentposition lässt sich daraus ohne weitere Annahmen nicht ablesen.',
 df:'Bei drei Abweichungen und einer Summe von 0 reichen zwei Angaben: Sind die ersten beiden −2 und +1, muss die letzte +1 sein. Das ist die Bindung durch den bereits geschätzten Mittelwert. Freiheitsgrade zählen hier die verbleibenden freien Abweichungen.',
 pearson:'Pearson beschreibt die lineare Komponente. Ein r nahe 0 kann mit einem deutlichen gekrümmten Muster einhergehen. Einzelne auffällige Punkte können r stark verändern. Die deskriptive Rechnung setzt keine Normalverteilung voraus; Aussagen über eine Grundgesamtheit benötigen zusätzliche Annahmen.',
 scaling:'Skalieren allein verschiebt den Mittelpunkt nicht auf 0. Hier ist der Maßstab die Standardabweichung. Im z-Rechenweg werden die Werte zuerst zentriert und dann skaliert. Nur diese Kombination ergibt z-Werte.',
 metric:'Nein. Zahlen können auch bloße Bezeichnungen sein, etwa 1 = Rot und 2 = Blau. Ob ein Abstand sinnvoll interpretierbar ist, ergibt sich aus der Messung und ihrer inhaltlichen Bedeutung.'
};
export default function App(){
 const [pairs,setPairs]=useState(readPairs),[view,setView]=useState(()=>initial(pairs)),[history,setHistory]=useState<View[]>([]),[viewId,setViewId]=useState(0),[highlight,setHighlight]=useState<string|null>(null),[storageError,setStorageError]=useState(false),[search,setSearch]=useState(''),[resetRevision,setResetRevision]=useState(0);
 const viewport=useRef<Viewport|undefined>(undefined),positions=useRef<Map<string,{x:number;y:number}>|undefined>(undefined);
 const context=useMemo(()=>lessonContext(pairs,view.caseId,view.route),[pairs,view.caseId,view.route]);
 const entry=entries.find(e=>e.id===view.entry)!,selected=view.selected,output=outputRef(selected),selectedKey=keyOf(selected),both=['pairs','crossproduct','crossproduct_sum','covariance','sd_product','pearson','linear'].includes(output.id);
 useEffect(()=>{try{localStorage.setItem(storageKey,JSON.stringify(pairs));setStorageError(false);}catch{setStorageError(true);}},[pairs]);
 function move(next:View,resetViewport=false){setHistory(h=>[...h.slice(-39),{...view,viewport:viewport.current,positions:positions.current}]);setView({...next,positions:undefined});setHighlight(null);if(resetViewport)setViewId(n=>n+1);}
 function select(r:Ref,caseId?:string){
  if(!conceptById[r.id])return;
  if(keyOf(r)===selectedKey&&(!caseId||caseId===view.caseId)&&!view.overview)return;
  const path=view.overview?null:findPath(view.focus,r,view.route),expanded=new Set(view.expanded);
  path?.slice(0,-1).forEach(item=>expanded.add(keyOf(item)));
  move({...view,entry:view.overview&&entries.some(e=>e.id===r.id)?r.id:view.entry,selected:r,variable:r.variable,caseId:caseId||view.caseId,focus:path?view.focus:r,expanded:path?expanded:new Set([keyOf(r)]),overview:false,viewport:undefined},!path);
 }
 function start(id:string){const root=ref(id,view.variable);move({...view,entry:id,focus:root,selected:root,expanded:new Set([keyOf(root)]),overview:false,viewport:undefined},true);}
 function expand(r:Ref){const expanded=new Set(view.expanded);if(expanded.has(keyOf(r)))expanded.delete(keyOf(r));else expanded.add(keyOf(r));move({...view,expanded,selected:r,variable:r.variable});}
 function drill(r:Ref){move({...view,entry:entries.some(e=>e.id===r.id)?r.id:view.entry,variable:r.variable,focus:r,selected:r,expanded:new Set([keyOf(r)]),overview:false,viewport:undefined},true);}
 function back(){const last=history.at(-1);if(!last)return;setHistory(h=>h.slice(0,-1));setView({...last,caseId:pairs.some(p=>p.id===last.caseId)?last.caseId:pairs[0].id});setHighlight(null);setViewId(n=>n+1);}
 function changePairs(next:DataPair[]){if(!validStoredPairs(next))return;setPairs(next);if(!next.some(p=>p.id===view.caseId))setView(v=>({...v,caseId:next[0].id}));}
 function changeVariable(variable:Variable){if(variable===view.variable)return;if(['pearson','covariance','crossproduct','crossproduct_sum','sd_product','pairs'].includes(view.focus.id)){select({...view.selected,variable});return;}const focus={...view.focus,variable},selected={...view.selected,variable};const expanded=new Set([...view.expanded].map(k=>k.replace(`:${view.variable}:`,`:${variable}:`)));move({...view,focus,selected,variable,expanded,viewport:undefined},true);}
 function changeRoute(route:Route){if(route===view.route)return;const root=ref('pearson',view.variable);move({...view,entry:'pearson',focus:root,selected:root,route,expanded:new Set([keyOf(root)]),overview:false,viewport:undefined},true);}
 const ingredients=inputs(selected,view.route).flatMap(r=>isOperation(r)?inputs(r,view.route):[r]),checks=conditions(selected,context),result=valueFor(selected,context);
 return <div className="atlas-app"><a className="skip-link" href="#explanation">Zur Erklärung springen</a><header className="app-header"><div><strong>Statistikatlas<span className="brand-dot">.</span></strong><span className="header-subtitle">Statistik aus Bausteinen verstehen</span></div><span className="header-note">Entdecken · Verändern · Nachvollziehen</span></header>
  <nav className="entry-nav" aria-label="Einstiege in den Baukasten">{entries.map((e,i)=><button key={e.id} aria-current={!view.overview&&view.entry===e.id?'page':undefined} onClick={()=>start(e.id)}><span>0{i+1}</span>{e.name}</button>)}</nav>
  <main><div className="lesson-intro"><div><span className="eyebrow">{view.overview?'Alle Begriffe, ein Baukasten':`${entry.name} entdecken`}</span><h1>{view.overview?'Die ganze Karte im Blick.':entry.question}</h1><p>{view.overview?'29 Begriffe bilden das gemeinsame Fundament. Wähle einen Begriff, um seinen eigenen Bauplan zu erkunden.':'Öffne einen Baustein. Verfolge seine Rechnung. Verändere die Daten.'}</p></div><button className={`overview-button ${view.overview?'active':''}`} onClick={()=>move({...view,overview:!view.overview,viewport:undefined},true)}><Grid2X2 size={18}/>{view.overview?'Zum Lernweg':'Alle 29 Bausteine'}</button></div>
  <div className="workspace-toolbar"><button className="back-button" disabled={!history.length} onClick={back}><ArrowLeft size={16}/>Zurück</button><nav className="breadcrumbs" aria-label="Aktueller Weg"><button onClick={()=>start(view.entry)}>{entry.name}</button>{keyOf(view.focus)!==keyOf(ref(view.entry,view.variable))&&<><span>/</span><button onClick={()=>drill(view.focus)}>{titleFor(view.focus)}</button></>}<span>/</span><span>{view.overview?'Gesamtkarte':titleFor(selected)}</span></nav>{!view.overview&&!both&&<div className="variable-control" role="group" aria-label="Variable betrachten">{(['x','y'] as Variable[]).map(v=><button key={v} aria-pressed={view.variable===v} onClick={()=>changeVariable(v)}>{v.toUpperCase()}<span> · {v==='x'?'Lernzeit':'Aufgaben'}</span></button>)}</div>}</div>
  {view.entry==='pearson'&&!view.overview&&<div className="route-control"><span>Rechenweg zu r</span><div role="group" aria-label="Rechenweg zu Pearson"><button aria-pressed={view.route==='covariance'} onClick={()=>changeRoute('covariance')}>Über die Kovarianz</button><button aria-pressed={view.route==='z'} onClick={()=>changeRoute('z')}>Über z-Werte</button></div><small>Gleiche Daten, gleiches Ergebnis.</small></div>}
  <div className={`workbench ${view.overview?'overview-workbench':''}`}><section className="map-panel" aria-label="Baukasten"><div className="map-heading"><span className="eyebrow">{view.overview?'Gesamtkarte':'Dein Bauplan'}</span><span>{view.overview?'Begriffe & ihre Beziehungen':'Von links nach rechts entsteht das Ergebnis'}</span></div><LearningGraph focus={view.focus} selected={selected} expanded={view.expanded} context={context} overview={view.overview} highlight={highlight} onSelect={select} onExpand={expand} onDrill={drill} viewId={viewId} restore={view.viewport} restorePositions={view.positions} onPositions={p=>{positions.current=p;}} onViewport={v=>{viewport.current=v;}}/><p className="map-caption">{view.overview?'Linie: Aufbau · gestrichelt: Voraussetzung · gepunktet: ergänzender Weg':'Mit + öffnest du die direkten Eingänge. Ziehe die Karte, um weitere Zweige zu sehen.'}</p></section>
   {!view.overview&&<section className="detail-panel" id="explanation" aria-labelledby="detail-title"><span className="eyebrow">{subtitle(selected)}</span><h2 id="detail-title" tabIndex={-1}>{titleFor(selected)}</h2><p className="concept-intro">{introduction(selected)}</p>{isOperation(selected)&&(selected.use||selected.id==='scaling')&&<p className="context-note">{selected.id==='scaling'?`Hier: uᵢ = ${selected.use==='z'?'zentrierter Wert':'ursprünglicher Wert'} von ${selected.variable.toUpperCase()}, a = Standardabweichung.`:`Hier: ${titleFor(output)}.`}</p>}
    <Formula key={`${selectedKey}-formal`} reference={selected} context={context} onSelect={select} onHighlight={setHighlight} highlight={highlight}/>
    <div className="calculation-heading"><span className="eyebrow">Mit deinen Daten</span><label>i = <select aria-label="Person für die Formel auswählen" value={view.caseId} onChange={e=>setView(v=>({...v,caseId:e.target.value}))}>{pairs.map((p,i)=><option value={p.id} key={p.id}>{i+1}</option>)}</select></label></div><p className="index-note">i bezeichnet die ausgewählte Person; bei Σ werden alle Personen durchlaufen.</p>
    <Formula key={`${selectedKey}-numeric`} reference={selected} context={context} onSelect={select} onHighlight={setHighlight} highlight={highlight} numeric/>
    {result!==null&&<div className="result-line" aria-live="polite"><strong>{numberText(result)}</strong>{unitFor(selected)&&<span>{unitFor(selected)}</span>}</div>}
    <p className="interpretation">{interpretation(selected,context)}</p>
    {checks.length>0&&<ul className="conditions" aria-label="Bedingungen und Annahmen">{checks.map((condition,i)=><li key={i} className={condition.ok===false?'unmet':condition.ok===true?'met':'assumption'}>{condition.ok===true?<Check size={15}/>:condition.ok===false?<CircleAlert size={15}/>:<Info size={15}/>}<span>{condition.text}{condition.target&&<button className="condition-link" onClick={()=>select(condition.target!)}>Erklären <span className="sr-only">{titleFor(condition.target)}</span></button>}</span></li>)}</ul>}
    {output.id==='pearson'&&<button className="text-button" onClick={()=>select(ref('linear'))}>Was bedeutet „linear“? <ArrowUpRight size={14}/></button>}
    {ingredients.length>0&&<div className="ingredients"><h3>Das geht ein</h3>{[...new Map(ingredients.map(r=>[keyOf(r),r])).values()].map(r=><button key={keyOf(r)} onClick={()=>select(r)}>{titleFor(r)} <span>{subtitle(r)}</span><ArrowUpRight size={13}/></button>)}</div>}
    <details key={`deep-${selectedKey}`} className="deep-explanation"><summary>{deepQuestions[output.id]||'Genauer verstehen'}</summary><p>{deepCopy[output.id]||conceptById[output.id]?.explanation}</p>{isOperation(selected)&&!selected.use&&<p>Hier steht a für den Wert der ausgewählten Person und b für den Wert der nächsten Person (nach der letzten wieder die erste).</p>}</details>
   </section>}
  </div>
  {view.overview?<section className="concept-library"><div className="section-heading"><div><span className="eyebrow">Direkt zu einem Begriff</span><h2>Deine Bausteinsammlung</h2></div><label className="search-label">Begriff finden<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="z. B. Varianz"/></label></div>{(['data','operation','summary','relationship'] as const).map(category=>{const matches=concepts.filter(c=>c.category===category&&`${titleFor(ref(c.id))} ${c.title} ${c.short}`.toLocaleLowerCase('de').includes(search.toLocaleLowerCase('de')));return matches.length?<div className="library-group" key={category}><h3>{({data:'Daten & Voraussetzungen',operation:'Rechenschritte',summary:'Kennwerte',relationship:'Zusammenhänge'})[category]}</h3><div>{matches.map(c=><button key={c.id} onClick={()=>drill(ref(c.id,view.variable))}><strong>{titleFor(ref(c.id))}</strong><span>{c.short}</span><ArrowUpRight size={17}/></button>)}</div></div>:null;})}{!concepts.some(c=>`${titleFor(ref(c.id))} ${c.title} ${c.short}`.toLocaleLowerCase('de').includes(search.toLocaleLowerCase('de')))&&<p>Kein Begriff gefunden. Versuche einen kürzeren Suchbegriff.</p>}</section>:<Experiment key={resetRevision} reference={selected} context={context} showBoth={both} onPairs={changePairs} onCase={caseId=>setView(v=>({...v,caseId}))} onReset={()=>{setResetRevision(n=>n+1);changePairs(defaultPairs.map(p=>({...p})));}}/>}
  {storageError&&<p className="storage-warning" role="status">Der Browser kann deine Änderungen gerade nicht speichern. Du kannst weiter experimentieren; nach dem Schließen gehen sie verloren.</p>}
  </main><footer><span>Statistikatlas · Grundlagen als Baukasten</span><span>Stichprobenkonvention: n − 1 · Zahlen gerundet (≈)</span><a href={location.protocol==='file:'?location.href:'./Statistikatlas-offline.html'} download="Statistikatlas-offline.html">Offline-Version herunterladen</a></footer>
 </div>;
}
