suppressPackageStartupMessages({library(mariposa); library(dplyr)})
options(warn = -1)
allbus <- read_spss("/Users/yannickdiehl/Documents/Universität Marburg/Lehre/Methoden Ib B.A./ZA8831_v1-3-0.sav")
allbus <- allbus %>% mutate(lage = rec(ep01, rules = "1:2=1 [gut]; 3=2 [teils/teils]; 4:5=3 [schlecht]; else=NA"))
print(allbus %>% filter(!is.na(ps03)) %>% group_by(lage) %>% summarise(n = n()))
cat("gamma eastwest x ps03 gesamt (gew.):", goodman_gamma(allbus, eastwest, ps03, weights = wghtpew), " V:", cramers_v(allbus, eastwest, ps03, weights = wghtpew), "\n")
print(allbus %>% filter(!is.na(lage)) %>% group_by(lage) %>% goodman_gamma(eastwest, ps03))
print(allbus %>% filter(!is.na(lage)) %>% group_by(lage) %>% cramers_v(eastwest, ps03))
cat("Anteil 'schlecht' (ep01 4-5) West/Ost:\n")
print(allbus %>% filter(!is.na(lage)) %>% group_by(eastwest) %>% summarise(schlecht = round(100*mean(lage == 3), 1)))
